### ISSUE TITLE
Epic crash

### ISSUE THREAD

**Issue by MuhXd** [ZiLko/xdBot#1]
https://github.com/ZiLko/xdBot/assets/100521306/d247f355-b909-4cb8-a23e-460f8eaffd74

**Comment by MuhXd** [comment]
i think spamming the load button did it after click one but i am not sure

**Comment by ZiLko** [comment]
Looking into it

**Comment by ZiLko** [comment]
I'm just gonna rework the file system to fix this + make it compatible with android, but it will take a while

**Comment by ZiLko** [comment]
Reworked the file system now, still happens with the import macro button, but i couldn't find a fix for it sadly
