### ISSUE TITLE
Lock 240 fps

### ISSUE THREAD

**Issue by CatWork2403** [ZiLko/xdBot#103]
Why did you lock it at 240 fps?There are a few heavy levels where I need the bot to be at 60 fps so that during the showcase it will be quite smooth, now you lock it at 240 fps so my phone can't stand it.

**Comment by WindowsAutomatic11** [comment]
This is so true!. I can't even bot explorers. It's laggy has hell. My phone is stronger.. and Xdbot made it slow?. That's dumb

**Comment by Seikatsuwem** [comment]
It is mostly for pc so it will be slow on mobile due to high demands from the mod.

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.2
