### ISSUE TITLE
Extremely Broken and buggy

### ISSUE THREAD

**Issue by DarkJBear** [ZiLko/xdBot#104]
It does not use clicks for accuracy anymore as shown with a cps counter, rotation is broken, wave trail works as if you are on moving D blocks, no spider trail from orbs or spider gamemode, no dash fire, settings button is broken, and extremely inaccurate

**Comment by ZiLko** [comment]
idk vro it woks for me

**Comment by ThunderPlayX** [comment]
Just because Zilko works for you, doesn't mean it also works for us, and I see that you no longer want to work on this mod, right?

**Comment by ZiLko** [comment]
its not even on geode vro of course i dont want to work on it anymore 💀

**Comment by ZiLko** [comment]
the bug you commented seems to happen randomly due to Geode not hooking a function properly or something

Ive only seen it happen once before and i hadnt even updated the bot in 3 months

**Comment by Draogn12345678** [comment]
i found the issue its because of click between frames it makes the mod really buggy so the wave is like on d-blocks and the orbs don't pulse on hit

**Comment by ZiLko** [comment]
💀

**Comment by LumerGD120** [comment]
Is there a reason that you don't want to work on it anymore?
