### ISSUE TITLE
random crashes everytime

### ISSUE THREAD

**Issue by roRyGD** [ZiLko/xdBot#106]
[2024-07-11_19-11-13.log](https://github.com/user-attachments/files/16185915/2024-07-11_19-11-13.log)

everytime i want to record a macro with xdbot it crashes in a random place of the level

**Comment by TheJake1** [comment]
I just have a script that doesn't work, do you know why?

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.2
