### ISSUE TITLE
Slow down and crash game

### ISSUE THREAD

**Issue by ThienGMD** [ZiLko/xdBot#108]
Zilko, please fix the game slowing down and crash game . Don't lock 240FPS

**Comment by Seikatsuwem** [comment]
what device are you on?
if on mobile, then it is slowing down due to high demands. If on pc, you have an old gpu/cpu or too many cache.

**Comment by ThienGMD** [comment]
> gpu

My phone is Nokia 5.4

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.2
