### ISSUE TITLE
some lost frames

### ISSUE THREAD

**Issue by PryzhokNaRobote** [ZiLko/xdBot#11]
https://github.com/ZiLko/xdBot/assets/156057628/9faf3ff1-127b-4405-9eee-cff571143e1d

can you fix it?

**Comment by ZiLko** [comment]
I think its fixed in next update

**Comment by PryzhokNaRobote** [comment]
Thanks! I will test it

вс, 11 февр. 2024 г., 00:53 ZIlko ***@***.***>:
