### ISSUE TITLE
wave trail bug

### ISSUE THREAD

**Issue by SmallName0** [ZiLko/xdBot#110]
once i record a macro with the wave the wave trail simply breaks when i play the macro
![image](https://github.com/user-attachments/assets/dd852d05-7eb3-43d0-8028-22f5cff46883)

**Comment by ZiLko** [comment]
do you have cbf

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.2
