### ISSUE TITLE
Crash 1.6.1

### ISSUE THREAD

**Issue by ThienGMD** [ZiLko/xdBot#115]
I was recording Schafs, suddenly it crash
[Crash 2024-08-06 10.03.21.dmp](https://github.com/user-attachments/files/16504902/Crash.2024-08-06.10.03.21.dmp)

**Comment by ThienGMD** [comment]
> ThienGMD?!

Yes

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.2
