### ISSUE TITLE
bot doesn't record clicks

### ISSUE THREAD

**Issue by Idontknow-121235** [ZiLko/xdBot#116]
when i make the macro or get one, the bot doesnt record clicks. it clearly says 0 CPS in the corner of my screeen
![Screenshot 2024-08-07 144555](https://github.com/user-attachments/assets/e2957277-56d5-4814-b66a-31c03e59b4da)
it just doesnt record the clicks. i clicked when i made the macro to jump and the clicks i guess just dont save

**Comment by ZiLko** [comment]
uninstall cbf
