### ISSUE TITLE
Not accuracy

### ISSUE THREAD

**Issue by ThienGMD** [ZiLko/xdBot#117]
I after bot SUPERMASOCHAMBER finished. I let it Play and I see it goes wrong and strange Trail Wave appears. Pls fix it
_Version 1.6.1_

**Comment by Arf1i** [comment]
Turn off CBF and set 240fps :)

**Comment by ThienGMD** [comment]
> Turn off CBF and set 240fps :)

I use mobile not pc

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.2
