### ISSUE TITLE
XD BOT MACRO BUG

### ISSUE THREAD

**Issue by Usrhhs2** [ZiLko/xdBot#118]
The wave trail is glitched when I play a macro using XD bot
![Screenshot 2024-08-11 033902](https://github.com/user-attachments/assets/1c91a380-2e3c-4368-8b64-0a22e52abf09)
![Screenshot 2024-08-11 033921](https://github.com/user-attachments/assets/ec47ea21-bdbe-487a-b80f-5c9b9f0dd30d)

**Comment by ZiLko** [comment]
do u have cbf

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.2
