### ISSUE TITLE
How to play bot on mobile 

### ISSUE THREAD

**Issue by HanzGD** [ZiLko/xdBot#120]
How to play bot on mobile

**Comment by HanzGD** [comment]
I've done it when I play the bot doesn't work

**Comment by HanzGD** [comment]
And when I die while doing the record action it changes back to 0 so it has to be 1 attempt for the bot to work.

**Comment by HanzGD** [comment]
@ZiLko 

https://github.com/user-attachments/assets/b73d97e3-5f19-4c31-83c5-ad259f007fd0

Look at the action, which was initially 2 when I died, it became 0 again

**Comment by ZiLko** [comment]
It's QOLmod

**Comment by HanzGD** [comment]
Oh the cause is qolmod?
@zilko

**Comment by ZiLko** [comment]
yes

**Comment by HanzGD** [comment]
Ok thanks
