### ISSUE TITLE
2.0.0 crash when attempting to load macro from file

### ISSUE THREAD

**Issue by 101Corp** [ZiLko/xdBot#125]
When I try to load a macro from a file, the game crashes. I hope this can be fixed soon as it means I can't load my existing macros for my levels. Thank you!
Crash report:
[2024-08-21_10-55-21.txt](https://github.com/user-attachments/files/16694163/2024-08-21_10-55-21.txt)

**Comment by ZiLko** [comment]
android or pc

**Comment by 101Corp** [comment]
pc

**Comment by firewyrm06** [comment]
Having this happen on android aswell

**Comment by ZiLko** [comment]
idk lets hope its fixed, the android one is
