### ISSUE TITLE
2.0.0 Wont record most the level 

### ISSUE THREAD

**Issue by CorruptedClan** [ZiLko/xdBot#128]
ive tried with both practice fix and not, so when making a macro and using checkpoints, the bot will only record the last/last two checkpoints, making it stressful and hard to record macros for harder levels

**Comment by ZiLko** [comment]
its qolmod, disable it

**Comment by ZiLko** [comment]
also wdym "with both practice fix and not" cus i dont think i let u disable it

**Comment by CorruptedClan** [comment]
alr ill try thx! is there other mods that have to be disabled (mod menus
like prism and qol) or is only qol?

sâm., 24 aug. 2024, 17:36 ZIlko ***@***.***> a scris:

**Comment by ZiLko** [comment]
not sure if other mod menus also break it
