### ISSUE TITLE
speedhack not turning off

### ISSUE THREAD

**Issue by koopatroopadoopa** [ZiLko/xdBot#132]
yk that theres that clock button near the pause button?
i think its the speedhack button 
whenever i click it the speed doesnt go to its regular speed
is this **normal?**

**Comment by koopatroopadoopa** [comment]
mevermind figured it out
1.0 is actually normal
0.5 just makes the game a bit slower
but please change 1.0 into normal game speed and not macro like speed

**Comment by ZiLko** [comment]
idk what you mean but if it is what i think it is then i already fixed it in next update
