### ISSUE TITLE
macro bug

### ISSUE THREAD

**Issue by koopatroopadoopa** [ZiLko/xdBot#133]
macro keeps crashing whenever i keep restarting a level

**Comment by ZiLko** [comment]
send crashlog, i probably already fixed it tho

**Comment by koopatroopadoopa** [comment]
> send crashlog, i probably already fixed it tho
![launcher_logcat.txt](https://github.com/user-attachments/files/16781276/launcher_logcat.txt)

**Comment by koopatroopadoopa** [comment]
here zilk

**Comment by ZiLko** [comment]
wtf is this

**Comment by ZiLko** [comment]
send geode crashlog imo

**Comment by koopatroopadoopa** [comment]
i did???

**Comment by ZiLko** [comment]
test in new release https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.2
