### ISSUE TITLE
it crashes when recording

### ISSUE THREAD

**Issue by randyjaja** [ZiLko/xdBot#134]
here's the crashlog: 
[2024-08-27_17-59-23.log](https://github.com/user-attachments/files/16770056/2024-08-27_17-59-23.log)

**Comment by ZiLko** [comment]
its either a qolmod crash or an incompatibility with it

**Comment by randyjaja** [comment]
> its either a qolmod crash or an incompatibility with it

i uninstalled qolmod and it works perfectly now, thanks
