### ISSUE TITLE
(v2.0.0) Macro Loading Crash

### ISSUE THREAD

**Issue by Eleazar4628** [ZiLko/xdBot#136]
When loading a macro, Geode simply crashes. (Android)
![Screenshot_2024-08-30-00-42-23](https://github.com/user-attachments/assets/cf92a595-463f-422e-a2c1-ffea960b5e58)

Log provided by Geode:
[Crash 2024-08-30 00.46.35.dmp](https://github.com/user-attachments/files/16811440/Crash.2024-08-30.00.46.35.dmp)
[launcher_logcat.txt](https://github.com/user-attachments/files/16811482/launcher_logcat.txt)

**Comment by ZiLko** [comment]
check latest release
