### ISSUE TITLE
(v2.0.0-alpha.2) Game freezes when loading a level

### ISSUE THREAD

**Issue by quuuut** [ZiLko/xdBot#138]
Freezes when loading any level, main or community. This isn't shown in previous versions.

(geode doesn't detect a crash so no log)

**Comment by ZiLko** [comment]
it doesnt crash it just freezes?

check if frame stepper is on

**Comment by quuuut** [comment]
frame stepper off, still freezes

**Comment by quuuut** [comment]
> it doesnt crash it just freezes?
> 
> 
> 
> check if frame stepper is on

ye

**Comment by ZiLko** [comment]
whats ur mod list

**Comment by ZiLko** [comment]
and send video if u can

**Comment by quuuut** [comment]
k

**Comment by quuuut** [comment]
https://github.com/user-attachments/assets/78a4737f-33d7-4127-9afa-1af4fa0b1d01

Mods:

bingy3.auto_delete v1.1.0
capeling.startpos_switcher v1.0.4
cvolton.betterinfo v4.2.8
cvolton.level-id-api v1.0.1
cvolton.misc_bugfixes v1.2.1
dankmeme.globed2 v1.5.1
firee.prism v1.9.0
flafy.autonong v0.3.1
fleym.nongd v2.11.0
geode.custom-keybinds v1.7.1
geode.node-ids v1.13.2
lilnibblit.chestalert v1.0.4
m336.autoleaderboard v1.0.0
m336.levelinfo v1.3.7
m336.modbadgeinfo v1.1.0
sabe.persistenceapi v1.0.0-alpha.2
sabe.platformersaves v1.0.1-alpha.3
spaghettdev.songpreview v1.1.0
techstudent10.discord_rich_presence v2.12.2
thesillydoggo.newgrounds_explorer v1.0.0-beta.1
zilko.xdbot v2.0.0-alpha.2

**Comment by quuuut** [comment]
Turning off Frame Stepper results in a "Load Failed" and kick
sorry, i was wrong

**Comment by quuuut** [comment]
Testing more, Toggling Show Layout on would fail to load the level and Frame Stepper would turn on when the level was clicked on

**Comment by ZiLko** [comment]
Load failed occurs in robtop levels, ill fix the frame stepper thing, thanks
