### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by LumerGD120** [ZiLko/xdBot#139]
Hi, Zilko i encountered a crash while botting Freedom08. **The crash happens when i click the restart button**, i can't put a video because of size limit.
Also here is the crash dmp

[Crash 2024-08-31 13.48.08.dmp](https://github.com/user-attachments/files/16823598/Crash.2024-08-31.13.48.08.dmp)

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.3 hopefully fixes it
