### ISSUE TITLE
crashing the game when i try to enter the pause menu

### ISSUE THREAD

**Issue by spookwav** [ZiLko/xdBot#14]
steps to recreate: play any level, press esc or pause button
crashlog: 
`2024-02-05T00:22:42+0000
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v2.0.0-beta.15
Loader Commit: d35b2de
Bindings Commit: 253a854
Installed mods: 24
Problems: 0

== Exception Information ==
Faulty Module: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 51BFAF07 (libcocos2d.dll + 6af07 (cocos2d::CCSet::removeAllObjects + 7))
Number Parameters: 2

== Stack Trace ==
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 6af07 (cocos2d::CCSet::removeAllObjects + 7)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 6ab0f (cocos2d::CCSet::~CCSet + 207)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 5f4bd (cocos2d::CCNode::addChild + 93)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + ac3af (cocos2d::CCMenu::addChild + 47)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 5f435 (cocos2d::CCNode::addChild + 21)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.node-ids\geode.node-ids.dll + 28c79
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.node-ids\geode.node-ids.dll + 27e29
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.node-ids\geode.node-ids.dll + 27ff1
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.node-ids\geode.node-ids.dll + 27d1c
 - 13E614EB
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 2ba57
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 191fb
 - 13E614EB
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\beat.click-sound\beat.click-sound.dll + 4e16
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\beat.click-sound\beat.click-sound.dll + 25fb
 - 13E614EB
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 2b89a8
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 2eaf9d
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3bfa08
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3bf943
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 9bf09 (cocos2d::CCKeyboardDispatcher::dispatchKeyboardMSG + 153)
 - 13F037E6
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\thesillydoggo.entersearch\thesillydoggo.entersearch.dll + 2274
 - 13F0360F
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 1eb54
 - 13F0360F
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + c7841 (cocos2d::CCEGLView::onGLFWKeyCallback + 481)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 116c7e (cocos2d::CCPoint::unrotate + 7998)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 1185d6 (cocos2d::CCPoint::unrotate + 14486)
 - C:\WINDOWS\System32\USER32.dll + 32e53 (Ordinal2713 + 1715)
 - C:\WINDOWS\System32\USER32.dll + 23c26 (CallWindowProcW + 1814)
 - C:\WINDOWS\System32\USER32.dll + 23597 (CallWindowProcW + 135)
 - C:\WINDOWS\system32\opengl32.dll + 3be09 (glDebugEntry + 3849)
 - C:\WINDOWS\System32\USER32.dll + 32e53 (Ordinal2713 + 1715)
 - C:\WINDOWS\System32\USER32.dll + 23c26 (CallWindowProcW + 1814)
 - C:\WINDOWS\System32\USER32.dll + 224e5 (DispatchMessageW + 1221)
 - C:\WINDOWS\System32\USER32.dll + 22030 (DispatchMessageW + 16)
 - C:\Program Files (x86)\Steam\gameoverlayrenderer.dll + 83090 (OverlayHookD3D3 + 121824)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 117472 (cocos2d::CCPoint::unrotate + 10034)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + c4dd0 (cocos2d::CCApplication::run + 720)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c12d8
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + c64b6 (geode::utils::web::AsyncWebRequest::userAgent + 12406)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c267e
 - C:\WINDOWS\System32\KERNEL32.DLL + 17ba9 (BaseThreadInitThunk + 25)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bd2b (RtlInitializeExceptionChain + 107)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bcaf (RtlClearBits + 191)

== Register States ==
EAX: 00000000
EBX: 00000004
ECX: 1f135c08
EDX: 7fffffff
EBP: 0135ebb0
ESP: 0135eb88
EDI: 1f135c08
ESI: 1f135c08
EIP: 51bfaf07

== Installed Mods ==
x | [v1.0.3] adam_729.deathmarkers
x | [v1.1.0] adyagd.godlikefaces
x | [v1.3.1] beat.click-sound
x | [v1.0.5] bitz.customprofiles
x | [v1.1.2] capeling.demons_in_garage_2.2
x | [v1.0.2] colon.bumpscosity
x | [v4.0.0-alpha.12] cvolton.betterinfo
x | [v1.0.0] ekv.save_on_level_page
x | [v1.0.3] firee.GoldenBest
x | [v2.2.4] fleym.nongd
x | [v2.0.0-beta.15] geode.loader
x | [v1.2.0] geode.node-ids
x | [v1.5.0] geode.texture-loader
x | [v1.0.0] itzkiba.formatted_platformer_time
x | [v1.2.0] legowiifun.unlisted_objects_in_editor
x | [v1.1.0] mat.scroll-zoom
x | [v1.0.4-beta.12] muhammadgames.bettermenu
x | [v1.2.1] shineua.minecraft_splash
x | [v1.0.0] thesillydoggo.entersearch
  | [v1.1.0] undefined0.minecraft_menu
x | [v1.0.2] weebify.restartbtn
x | [v1.0.1] xanii.flashlight
x | [v1.3.4] zilko.xdbot
  | [v0.1.2] zohnannor.dark_mode
`
after some testing it is definitely xdbot crashing the game.

**Comment by ZiLko** [comment]
apparently fixed on next update
