### ISSUE TITLE
how to install with geode v3.4.0

### ISSUE THREAD

**Issue by Toni500github** [ZiLko/xdBot#143]
I have searched on the geode index and nothing appears, always database busy.\
Then I tried downloading from the releases and gets always stuck on the loading screen saying
![image](https://github.com/user-attachments/assets/19e8f153-1a31-4391-ad2f-2a64a91af8f1)

I have tried with latest release [v2.0.0-alpha.3](https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.3) and [v1.5.5](https://github.com/ZiLko/xdBot/releases/tag/v1.5.5) but nothing

**Comment by ZiLko** [comment]
data busy thing is not related to xdbot

**Comment by Toni500github** [comment]
Yes I know right.

But is there a way to install it from the GitHub releases? On which version does it work without getting stuck on the loading screen?
