### ISSUE TITLE
Macros do not play correctly

### ISSUE THREAD

**Issue by MonkeyInPrivite** [ZiLko/xdBot#144]
I made a bloodlust macro and it seems to be broken. I believe this is an issue where if you start recording in practice mode, when you enter practice mode it will not restart the level so the macro will be recorded with an offset.

**Comment by ZiLko** [comment]
send the broken macro

**Comment by ZiLko** [comment]
it does restart the level automatically when you enter practice mode

**Comment by ZiLko** [comment]
android or pc

**Comment by ZiLko** [comment]
how much speedhack did you use

**Comment by ZiLko** [comment]
tell me what mods do u have, u can send screenshots if you want

**Comment by ZiLko** [comment]
try removing click on steps

**Comment by ZiLko** [comment]
and dont use physics bypass

**Comment by ZiLko** [comment]
what mod did you use to physics bypass

**Comment by ZiLko** [comment]
u have to record a new macro

**Comment by ZiLko** [comment]
cus the old one is broken forever

**Comment by ZiLko** [comment]
try recording the first 20% of bloodlust and see if it breaks

**Comment by ZiLko** [comment]
can u try with no other mods other than xdbot, node ids, and custom keybinds
