### ISSUE TITLE
Renderer not working

### ISSUE THREAD

**Issue by Gleiverx** [ZiLko/xdBot#146]
When I click on start and try to render, it crashes my game

**Comment by Gleiverx** [comment]
Yeah I'm on it

**Comment by ZiLko** [comment]
does it give u a crashlog

**Comment by Gleiverx** [comment]
No it dosent. it's like when I click on start and press either the resume button or the restart button, it freezes my game for like some seconds and then closes my game. When I check the file where your videos are it does show me a file but it says the file is unsupported or is corrupted. (Cpu is intel and graphics card is nvidia)

**Comment by ZiLko** [comment]
ill fix

**Comment by ZiLko** [comment]
fixed in

https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.4
