### ISSUE TITLE
Can't record a macro on platformer.

### ISSUE THREAD

**Issue by ZSansBy20** [ZiLko/xdBot#148]
It doesn't matter if I hit play or record, as soon as I hit play or restart, the game crashes.

**Comment by ZiLko** [comment]
send crashlog

**Comment by ZiLko** [comment]
possibly fixed in alpha 4 if it didnt have a crashlog

https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.4

**Comment by ZiLko** [comment]
nvm i didnt fix it but i know how to

**Comment by ZiLko** [comment]
it happens with death tracker

**Comment by ZSansBy20** [comment]
O
