### ISSUE TITLE
another problem with show layout 🔥🔥🗣️🗣️

### ISSUE THREAD

**Issue by AcePainiteGitHub** [ZiLko/xdBot#149]
forgot to mention this with the previous issue but there is the second problem with show layout related to the teleport portals

show layout would also remove objects with a blue teleport portal linked

**Comment by ZiLko** [comment]
O, will fix

im not a 2.2 expert so i dont know all object properties and stuff so keep reporting stuff like this if u find more

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.5
