### ISSUE TITLE
How to get renderer working on android?

### ISSUE THREAD

**Issue by jcesmas** [ZiLko/xdBot#150]
![Screenshot_20240903-103721](https://github.com/user-attachments/assets/2c966bd6-48c5-41d8-be94-4736bf6205a4)
It says it needs a ffmpeg.exe path to use for renderer, but I don't really know any way of doing that for android in any way. Can someone please please tell me if it is doable or not for android?

**Comment by HiimAndrew123** [comment]
well to answer your question no render does not work on mobile
in previous updates, the entire thing was greyed out so yeah
