### ISSUE TITLE
render bug (windows)

### ISSUE THREAD

**Issue by matvey-byte46** [ZiLko/xdBot#152]
when I assigned "_amf" to h264, and re-entered, I seen this:

![Geometry Dash 04 09 2024 18_51_52](https://github.com/user-attachments/assets/ab18dce7-1310-40eb-a358-2f1d644eb56f)

crashlog: 
![Запись 04 09 2024 19_00_46](https://github.com/user-attachments/assets/c64df655-16a6-411f-8600-56db85941662)
(It happened clicked on speedhack)

if this is a bug, please, fix it, zilko.

// matvey46 //

**Comment by ZiLko** [comment]
what mods do u have

**Comment by ZiLko** [comment]
just send the crashlog so i can see modlist

**Comment by matvey-byte46** [comment]
> just send the crashlog so i can see modlist

[2024-09-04_20-13-13.log](https://github.com/user-attachments/files/16874480/2024-09-04_20-13-13.log)

**Comment by ZiLko** [comment]
its betterinputs

**Comment by ZiLko** [comment]
i have no idea why betterinputs does that so just disable it for now
