### ISSUE TITLE
Sound Effects dont play in rendered footage

### ISSUE THREAD

**Issue by NothingIsScary** [ZiLko/xdBot#153]
Not really an "Issue" but more of a suggestion.
Idk how hard this would be but maybe you could make the renderer put the level's sound effects in the showcase alongside the song.

**Comment by ZiLko** [comment]
adding sound effects with its settings manually wouldnt be effective

so im just gonna record the game's audio and add it to the video

**Comment by NothingIsScary** [comment]
Do you plan to make the renderer do that for you or?

**Comment by ZiLko** [comment]
its gonna automatically record audio on another attempt

**Comment by NothingIsScary** [comment]
sick
