### ISSUE TITLE
Crash when load .gdr macro on android

### ISSUE THREAD

**Issue by ReoGentO** [ZiLko/xdBot#155]
In the latest version after saving .gdr macro it can't be loaded. But on the version below everything works fine. (without any logs...)

**Comment by ZiLko** [comment]
send macro file

**Comment by ReoGentO** [comment]
> send macro file

[Mirror Death Impossible Level.zip](https://github.com/user-attachments/files/16902299/Mirror.Death.Impossible.Level.zip)

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.5
