### ISSUE TITLE
Something is wrong...

### ISSUE THREAD

**Issue by Unalized** [ZiLko/xdBot#161]
Clearing macro not working, load becomes "koad"?, icon didn't move when playing macro, PLSS FIX IT

**Comment by ZiLko** [comment]
do u have frame stepper on

that might be why ur icon isnt moving

**Comment by Unalized** [comment]
No I don't

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.8
