### ISSUE TITLE
CBF BUG

### ISSUE THREAD

**Issue by v1st3rr** [ZiLko/xdBot#163]
So i just discovered if you have cbf in geofe then xdbot will automatically turn off without a reason even if you disabled cbf, but when m completely deleting cdf, everything works fine, zilko fix this plz

**Comment by ZiLko** [comment]
i cant fix its a geode bug

**Comment by v1st3rr** [comment]
> i cant fix its a geode bug
:(

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.9
