### ISSUE TITLE
This not an issue but...

### ISSUE THREAD

**Issue by Unalized** [ZiLko/xdBot#164]
Can you add like accurate speedhack in the next update? It's hard to bot sometimes with the lowest current speedhack is 0.1

**Comment by ZiLko** [comment]
I didnt even know it was inaccurate so this is pretty much an issue xd

**Comment by Micah1101** [comment]
> I didnt even know it was inaccurate so this is pretty much an issue xd

you mean xd[bot]                     ok ill stop
