### ISSUE TITLE
Load Macro button typo

### ISSUE THREAD

**Issue by NothingIsScary** [ZiLko/xdBot#167]
It says Koad

![322170_20240913005247_1](https://github.com/user-attachments/assets/c91d8c80-6fca-42bd-95db-e0b80d2ab65b)

**Comment by Unalized** [comment]
Missclick you know? K and L are close

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.6
