### ISSUE TITLE
Renderer bugged with 2.2 levels

### ISSUE THREAD

**Issue by TheUniverseIsKing** [ZiLko/xdBot#168]
The final video seems to be bugged/glitched from the renderer tool.. It looks like some 2.2 triggers are causing the bug and it concerns most 2.2 levels (new generation of 2.2 levels after december 2023 - not the 2.2 levels beetween 2017 and the actual release of the update in 2023). The glicth can be stronger and animated on some levels depending to the strength and use of the triggers or maybe something else used in 2.2 levels

![Capture d'écran 2024-09-14 104401](https://github.com/user-attachments/assets/9d114d46-7db7-49b9-836e-38acee78c66d)

**Comment by ZiLko** [comment]
Its shaders, theres a temporary fix in render settings called "Fix Shaders"
