### ISSUE TITLE
Crashes the game when i die twice

### ISSUE THREAD

**Issue by amongusbadcoder** [ZiLko/xdBot#170]
2024-09-14T20:58:58+0700
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v3.5.0
Loader Commit: ebd65ca
Bindings Commit: bd13cd0
Installed mods: 19
Problems: 3

== Exception Information ==
Faulty Module: E:\Saved Games\gd\2.206 yaeayeayeya\geometrydash1.exe
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 00007FF77A9A0FA8 (geometrydash1.exe + 60fa8)
Number Parameters: 2
Crashed thread: Main

== Stack Trace ==
 - E:\Saved Games\gd\2.206 yaeayeayeya\geometrydash1.exe + 60fa8
 - E:\Saved Games\gd\2.206 yaeayeayeya\geometrydash1.exe + 39246d
 - E:\Saved Games\gd\2.206 yaeayeayeya\geometrydash1.exe + 3941bd
 - 0000026DE579F472 (Hook handler)
 - E:\Saved Games\gd\2.206 yaeayeayeya\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 107f48
 - E:\Saved Games\gd\2.206 yaeayeayeya\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + f94de
 - 0000026DE579F472 (Hook handler)
 - E:\Saved Games\gd\2.206 yaeayeayeya\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 107f48
 - E:\Saved Games\gd\2.206 yaeayeayeya\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 287d5
 - 0000026DE579F472 (Hook handler)
 - E:\Saved Games\gd\2.206 yaeayeayeya\geometrydash1.exe + 395e26
 - 0000026DE579F072 (Hook handler)
 - E:\Saved Games\gd\2.206 yaeayeayeya\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 1087f1
 - E:\Saved Games\gd\2.206 yaeayeayeya\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 10636
 - 0000026DE579F072 (Hook handler)
 - E:\Saved Games\gd\2.206 yaeayeayeya\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 1087f1
 - E:\Saved Games\gd\2.206 yaeayeayeya\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 60e3d
 - 0000026DE579DC72 (Hook handler)
 - E:\Saved Games\gd\2.206 yaeayeayeya\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 10372b
 - E:\Saved Games\gd\2.206 yaeayeayeya\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 45bd3
 - 0000026DE579DC72 (Hook handler)
 - E:\Saved Games\gd\2.206 yaeayeayeya\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 10372b
 - E:\Saved Games\gd\2.206 yaeayeayeya\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + c726
 - 0000026DE579DC72 (Hook handler)
 - E:\Saved Games\gd\2.206 yaeayeayeya\geometrydash1.exe + 227df7
 - 0000026DE7BB0072 (Hook handler)
 - E:\Saved Games\gd\2.206 yaeayeayeya\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 103acb
 - 0000026DE7BB0072 (Hook handler)
 - E:\Saved Games\gd\2.206 yaeayeayeya\libcocos2d.dll + c041d (cocos2d::CCScheduler::update + 141)
 - 0000026DE5654472 (Hook handler)
 - E:\Saved Games\gd\2.206 yaeayeayeya\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 15444
 - 0000026DE5654472 (Hook handler)
 - 0000026DE5654472 (Hook handler)
 - E:\Saved Games\gd\2.206 yaeayeayeya\libcocos2d.dll + bbc24 (cocos2d::CCDirector::drawScene + 36)
 - 0000026DE7BB1072 (Hook handler)
 - 0000026DE7BB1072 (Hook handler)
 - E:\Saved Games\gd\2.206 yaeayeayeya\libcocos2d.dll + bc33b
 - E:\Saved Games\gd\2.206 yaeayeayeya\libcocos2d.dll + 72cd2 (cocos2d::CCApplication::run + 1122)
 - E:\Saved Games\gd\2.206 yaeayeayeya\geometrydash1.exe + 4a2d69
 - E:\Saved Games\gd\2.206 yaeayeayeya\Geode.dll + 24aaca (gdMainHook + 554 | /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:167)
 - E:\Saved Games\gd\2.206 yaeayeayeya\geometrydash1.exe + 4a415a
 - C:\WINDOWS\System32\KERNEL32.DLL + 1257d (BaseThreadInitThunk + 29)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 5af28 (RtlUserThreadStart + 40)

== Register States ==
RAX: 0000026d8d2d2a50
RBX: 0000000000000000
RCX: 000000007ffe0380
RDX: 0000000000c70353
RBP: 0000000000000000
RSP: 0000008e86effa20
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00007ffe0590af28
R8:  00000000000000c7
R9:  0000000000000040
R10: 00000000000000c0
R11: 0707b0c63f6bf076
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
  | [v4.2.8] cvolton.betterinfo
x | [v1.0.1] cvolton.level-id-api
  | [v1.2.0-beta.2] cvolton.misc_bugfixes
  | [v1.5.1] dankmeme.globed2
  | [v0.3.1] flafy.autonong
  | [v2.11.0] fleym.nongd
x | [v1.7.1] geode.custom-keybinds
x | [v3.5.0] geode.loader
x | [v1.13.2] geode.node-ids
  | [v1.1.0] hjfod.backups
  | [v6.7.0] hjfod.betteredit
! | [v1.3.0] hjfod.bettersave
  | [v1.2.1] hjfod.gmd-api
! | [v1.0.0] hjfod.trashcan
! | [v2.11.1] maxnu.gd_mega_overlay
  | [v1.3.0] nytelyte.wave_trail_drag_fix
  | [v1.6.0] thesillydoggo.qolmod
x | [v1.2.0] weebify.separate_dual_icons
x | [v2.0.0-alpha.1] zilko.xdbot

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.6 😭
