### ISSUE TITLE
Game crashes if you pull up the menu too fast while level screen is loading

### ISSUE THREAD

**Issue by NothingIsScary** [ZiLko/xdBot#171]
This is a easily reproducible issue as shown in this video.

https://github.com/user-attachments/assets/0b8848a4-428c-4bae-9e21-a9cc93b799ff

**Comment by ZiLko** [comment]
O thanks, will fix next update

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.8
