### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Micah1101** [ZiLko/xdBot#174]
![Screenshot 2024-09-14 233639](https://github.com/user-attachments/assets/ca849039-598f-4137-b6a2-1a265e321294)
Whenever I add it to my geode mods folder, it just says Error Loading Mods, how do i fix?

**Comment by MyDadWentWihatj** [comment]
It's normal. Just go to the last page scroll down and you find xdbot

Have you insert into geode?

**Comment by Helloausername** [comment]
enable node ids and custom keybinds, u need those on every platform

**Comment by Micah1101** [comment]
> enable node ids and custom keybinds, u need those on every platform

i already have node ids and custom keybinds tho

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.6 fixes

**Comment by Micah1101** [comment]
> https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.6 fixes

thank you so much!
