### ISSUE TITLE
Game freezes when loading level

### ISSUE THREAD

**Issue by TheQuestLegend** [ZiLko/xdBot#177]
if i enable the mod then try to play a level, it freezes and i have to force close the game; this is the frame it gets stuck on:
![image_2024-09-15_064806807](https://github.com/user-attachments/assets/04636cf1-fe8e-44ce-9e12-0f785fb853ae)

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.6

**Comment by ZiLko** [comment]
if it keeps happening submit new issue
