### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Helloausername** [ZiLko/xdBot#178]
Game crashes without crashlog on android32 bit

Mods:
Rainbow icons, custom keybinds, globed,node ids, startpos switcher.

**Comment by ZiLko** [comment]
vro tell me WHEN it crashes

**Comment by ZiLko** [comment]
like what are the steps to crash, open a level?, pause the game?, respawn in a checkpoint?

**Comment by ZiLko** [comment]
and im assuming that mod list includes xdbot too

**Comment by Helloausername** [comment]
> and im assuming that mod list includes xdbot too

Yeah and heres how: enter a level with the trajectory thing on, play for some minutes and it will crash (only platformer levels)

**Comment by Helloausername** [comment]
Im not sure if its a crash with globed but i will try without in a globed server

**Comment by Helloausername** [comment]
nvm its prob a bug with globed
