### ISSUE TITLE
Bugggg on mobile

### ISSUE THREAD

**Issue by Amoodee10** [ZiLko/xdBot#18]
So, when i install it on mobile it says that it doesn't support the current gd version. Or was it doesn't meant for mobile?

Plus, if it supports mobile, can you update so it supports the latest gd version.

Thank you

**Comment by Amoodee10** [comment]
Plz do it fast

**Comment by ZiLko** [comment]
It's not available for mobile

**Comment by Amoodee10** [comment]
> It's not available for mobile

Thanks

But can i somehow use your mode and convert it to mobile friendly *although i dont really know how to code*? And the gui seems to be mobile friendly btw

(｡•̀ᴗ-)✧

**Comment by Amoodee10** [comment]
If can't, i dont care lol

Thank youu
