### ISSUE TITLE
Bot menu crashes when I want to open it again. and it happened on my 64 bit phone :(

### ISSUE THREAD

**Issue by RainbowRain777** [ZiLko/xdBot#180]
Uploading lv_0_20240916041623.mp4…

**Comment by RainbowRain777** [comment]
https://github.com/user-attachments/assets/25620758-d88a-4e5f-8a7d-bd5d025ebf69


The case is like this

**Comment by ZiLko** [comment]
i see, close it from the X button for now

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.8
