### ISSUE TITLE
X and Y Position bug for player 1

### ISSUE THREAD

**Issue by WhenTheBegininging** [ZiLko/xdBot#181]
so like the title said there is X and Y Position bug for player 1
and the proof is somewhere
![image_2024-09-16_065708082](https://github.com/user-attachments/assets/9cee818e-0dd4-4716-a3a6-850556ee380b)
and as you can see it is **_SEPARATING_**
also the X and Y Position bug for player 1 can be received by spamming the checkpoint over and over again until it **noclips HALF OF THE SPIKE**
so thats all, if you see this and you will fix it thank you.

**Comment by WhenTheBegininging** [comment]
and here is another proof
![image_2024-09-16_070030847](https://github.com/user-attachments/assets/e3f1f3bf-2920-4eb8-b316-71f09d4ad063)

**Comment by ZiLko** [comment]
i dont think this is a xdbot bug? can you try without any other mods

**Comment by WhenTheBegininging** [comment]
this is pure xdbot 2.0.0 and without any TPS bypass

**Comment by ZiLko** [comment]
send video replication

**Comment by WhenTheBegininging** [comment]
https://streamable.com/z7s7b6

**Comment by ZiLko** [comment]
Hai, theres a mod thats letting you place checkpoints while dead, this is not vanilla behavior and its essentially whats causing the bug

**Comment by ZiLko** [comment]
Hai, theres a mod thats letting you place checkpoints while dead, this is not vanilla behavior and its essentially whats causing the bug

**Comment by WhenTheBegininging** [comment]
Ok, but what is the mod called, i dont see anything wrong

**Comment by ZiLko** [comment]
vro idk what mod is it, just dont place checkpoints while youre dead
