### ISSUE TITLE
Whenever I use a dash orb the macro gets totally ruined.

### ISSUE THREAD

**Issue by IDaOiI** [ZiLko/xdBot#189]
I uploaded a video to showcase it on youtube, since it's too big to upload here
https://youtu.be/wgLA7JZLFjY

here is another previous instance of this on another showcase
https://youtu.be/wGsPIzpbrZc

Is there any way to fix this?

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.90
