### ISSUE TITLE
Text fields filled by whatever was last inputed

### ISSUE THREAD

**Issue by mbdavis1213** [ZiLko/xdBot#190]
![Screenshot 2024-09-22 083508](https://github.com/user-attachments/assets/8507f370-2418-4ae4-a0a0-3733c4e5909b)

I am trying to record a showcase for a friend, and this thing won't allow me to, because any time I try to correct it, they all screw up. Please fix this.

**Comment by ZiLko** [comment]
Disable betterinputs
