### ISSUE TITLE
Fix shader crash

### ISSUE THREAD

**Issue by TheUniverseIsKing** [ZiLko/xdBot#192]
Whenever I turn the fix shader and then start the rendering it automatically crashes/shuts down the command prompt window needed to process the rendering (and then error message | There was an error saving the render. ID : 12)

**Comment by ZiLko** [comment]
Enable platform console in geode settings and send me screenshot of what it says when the error shows up

**Comment by TheUniverseIsKing** [comment]
> Enable platform console in geode settings and send me screenshot of what it says when the error shows up

![Capture d'écran 2024-09-23 182418](https://github.com/user-attachments/assets/e1ac9af6-b91c-4a7d-8a87-f33ee351e45b)

**Comment by ZiLko** [comment]
o i fixed next update i think ill send it here when i release

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.90
