### ISSUE TITLE
i cant open it my version is lastest

### ISSUE THREAD

**Issue by anhbi123** [ZiLko/xdBot#193]
my bot is appear N/A icon and i cant open it

**Comment by ZiLko** [comment]
does it show error

**Comment by anhbi123** [comment]
> does it show error

yeah i cant enable it

**Comment by ZiLko** [comment]
what error

**Comment by anhbi123** [comment]
> what error

i just cant enable it,does this mod in geode because i see the N/A icon when i add it to geode
