### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by RainbowRain777** [ZiLko/xdBot#195]
I don't know if this is a bug or not. but when playing the macro the first time after starting the level, the frames don't run smoothly

https://github.com/user-attachments/assets/17e31f2f-b2e4-4ef9-b0f0-26694324a77b

**Comment by RainbowRain777** [comment]
Android only (for PC Idk lol)

**Comment by ZiLko** [comment]
intentional, its restarting on the first attempt
