### ISSUE TITLE
Ability to upload your own macros for online use

### ISSUE THREAD

**Issue by Harameen** [ZiLko/xdBot#199]
It would be cool to be able to upload your own macros and download other people's macros. This could be implemented via Github I think. Auto nong works something like this.

**Comment by melon2212** [comment]
id like that, also I made a deadlocked macro
[Deadlocked.gdr.json](https://github.com/user-attachments/files/17176119/Deadlocked.gdr.json)

**Comment by melon2212** [comment]
forgot it kills you.

**Comment by melon2212** [comment]
[Deadlocked fixed.gdr.json](https://github.com/user-attachments/files/17176179/Deadlocked.fixed.gdr.json)
fixed version

**Comment by ZiLko** [comment]
provably not doing this
