### ISSUE TITLE
merge recording to fix a bug

### ISSUE THREAD

**Issue by Toni500github** [ZiLko/xdBot#20]
i was show casing Butiti III with [GDMegaOverlay](https://github.com/maxnut/GDMegaOverlay) for speedhack and it was lagging a lot (Nvidia GTX 1650 with AMD Ryzen 5500). after completing the level, I played it and there was a bug (the only one) where I need to use noclip
![image](https://github.com/ZiLko/xdBot/assets/88878648/55ca8be6-3b62-467e-ae17-5e27821596bb)

Since i want to avoid using noclip for making gameplay seem more legit, is there a way that: The bot play the level, then when it arrives at some point I start recording it again and then merge those 2 replays togheter? or something else? It was a really difficult level to record with lag spikes

**Comment by ZiLko** [comment]
You can play the macro in practice while placing checkpoints, then when you get there, place a checkpoint then click record, and record from there up to the end

Unfortunately there isnt a way to merge macros yet

**Comment by ZiLko** [comment]
Also just use ldm while recording the level, then you can play the macro without ldm

**Comment by Toni500github** [comment]
> Also just use ldm while recording the level, then you can play the macro without ldm

100 QI idea

**Comment by Toni500github** [comment]
> You can play the macro in practice while placing checkpoints, then when you get there, place a checkpoint then click record, and record from there up to the end
> 
> Unfortunately there isnt a way to merge macros yet

I'm actually a mad man. 

I followed this suggestion, so I played the macro and arrived to a certain point I started recording and then I stopped when there was a part where I can stop. 

Once saved the macro, since the macros are plain text (thank you so much for not making those binary) what I did was to open both the original and the new recorded macro on a text editor, then I was searching to the latest 1st digits that the macros has in common (e.g 519|...)

And there, on the original I started to delete from the begging to the number that both has in common, then I selected all the text from the new macro (CTRL+A) then copy-pasted it on the original and 

**IT WORKS!!!**

**Comment by ZiLko** [comment]
That also works, macro merger would do that but automatically
