### ISSUE TITLE
rendering error ID:12

### ISSUE THREAD

**Issue by melon2212** [ZiLko/xdBot#201]
what does that mean?
![image](https://github.com/user-attachments/assets/4c8f4125-70de-4e55-926a-70d1345ce3bf)

**Comment by ZiLko** [comment]
Args or codec are invalid

**Comment by melon2212** [comment]
how do i configure those

**Comment by melon2212** [comment]
![image](https://github.com/user-attachments/assets/32b45fa1-dbf5-4ca6-9d56-d8b50a936601)
these are the arg configuration, default.

**Comment by melon2212** [comment]
![image](https://github.com/user-attachments/assets/a4ef4674-f2ba-430d-970d-ca7e5b2a2e05)
this, is it supposed to be folder or .exe

**Comment by melon2212** [comment]
![image](https://github.com/user-attachments/assets/10d3d519-f7be-464a-8e5f-d55711b89556)
image of the error for people who haven't gotten it yes

**Comment by ZiLko** [comment]
whats ur codec

**Comment by melon2212** [comment]
idk

**Comment by melon2212** [comment]
how do I find the codec

**Comment by melon2212** [comment]
where's the "?" at?

**Comment by melon2212** [comment]
![image](https://github.com/user-attachments/assets/fc1f7038-9b01-4dae-8c9e-0191c32112b6)

**Comment by ZiLko** [comment]
vro whats the width and height u set?

**Comment by melon2212** [comment]
how do I do that

**Comment by melon2212** [comment]
fixed it and game crashed afterwards lol
