### ISSUE TITLE
UI won't function on my device

### ISSUE THREAD

**Issue by Nolan0027** [ZiLko/xdBot#202]
The UI for the bot wont work for my device (a galaxy tab S7), what I mean is when i open the menu and try to do stuff nothing reacts to touch

**Comment by ZiLko** [comment]
what mods

**Comment by Nolan0027** [comment]
I had QOLmod but i disabled it and the UI works sometimes but still sometimes remains frozen

**Comment by Ziyxc1** [comment]
Do you use text select mod?

**Comment by Nolan0027** [comment]
Yes

**Comment by ZiLko** [comment]
uninstall it
