### ISSUE TITLE
It doesnt function with something thats active (but its on default games value)

### ISSUE THREAD

**Issue by Nolan0027** [ZiLko/xdBot#208]
Deleting text select mod made it work but i have a mod menu that lets you edit the games tps, right now its on 240 (the games defualt) but the mod says it doesnt work, why is this?
![Screenshot_20240929_131216_Geode](https://github.com/user-attachments/assets/bc12b468-8846-4cdb-a14b-02714715635b)

**Comment by ZiLko** [comment]
o set it to something else then 240 again
