### ISSUE TITLE
Crwsh with big macro (android)

### ISSUE THREAD

**Issue by Button-Pushing** [ZiLko/xdBot#210]
I made a big macro of deadlocked and when it finishes the game crashes

**Comment by ZiLko** [comment]
send crashlog

**Comment by ZiLko** [comment]
and send macro

**Comment by Button-Pushing** [comment]
Where do I find the macro

**Comment by Button-Pushing** [comment]
[Crash 2024-10-01 07.45.45.dmp](https://github.com/user-attachments/files/17211599/Crash.2024-10-01.07.45.45.dmp)

**Comment by ZiLko** [comment]
old crashlog
