### ISSUE TITLE
ooh duals are bugging when playing macros

### ISSUE THREAD

**Issue by window01gd** [ZiLko/xdBot#212]
hello! i have an issue. all information is below. I am using the latest version of xdbot
macro was recorded on a **2.0.0 beta 2 or beta 3** version of xdbot, latest update of geode is installed
second player is _teleporting_ to the ground and can't move but icon rotates(it's visible at wave)
_it does not happen with .gdr macros, only to .json format_
here is the video
note: **current level does not have two player mode** and also I use android x64

https://github.com/user-attachments/assets/72ce7b8d-0d96-481b-b5b1-0f57d35a0e97

**Comment by window01gd** [comment]
any thoughts?

**Comment by ZiLko** [comment]
fixed in beta 4 but if ur macro is broken record a new one or send it here so i can fix it

**Comment by window01gd** [comment]
> fixed in beta 4 but if ur macro is broken record a new one or send it here so i can fix it

ok i will record a new one and see
i opened new issue because this successful-recorded macros dont work anymore because of new version

**Comment by window01gd** [comment]
[Sakupen Circles.gdr.json](https://github.com/user-attachments/files/17190879/Sakupen.Circles.gdr.json)
@ZiLko here is the macro
also why in files macros have .gdr.json format?

**Comment by window01gd** [comment]
> ok i will record a new one and see
> i opened new issue because this successful-recorded macros dont work anymore because of new version
> 
> 
i have just recorded a new macro and that bug disappeared
it means that all .json macros that was recorded before beta 4 are broken

**Comment by ZiLko** [comment]
no the ones recorded in beta.3 and in a dual are
