### ISSUE TITLE
spider appears upside-down 

### ISSUE THREAD

**Issue by melon2212** [ZiLko/xdBot#213]
![image](https://github.com/user-attachments/assets/4133e726-887b-47a7-8602-639821008550)
this is proof

**Comment by melon2212** [comment]
https://github.com/user-attachments/assets/c26515ce-6672-48b2-bef9-7220fa91e6ff

more proof

**Comment by melon2212** [comment]
it even has hitboxes on for proof

**Comment by ZiLko** [comment]
are you playing a macro, send it

**Comment by ZiLko** [comment]
what mods do you have

**Comment by ZiLko** [comment]
this sounds like another mod cus another guy got it fixed without me doing anything
