### ISSUE TITLE
Platformer Time is always displayed

### ISSUE THREAD

**Issue by mariokirby1703** [ZiLko/xdBot#214]
When playing any Platformer Level there is an additional Platformer Time at the bottom of the Screen that you cant turn off.

**Comment by ZiLko** [comment]
???? send screenshot

**Comment by mariokirby1703** [comment]
seems to be a specific mod combination that does this.
on my normal usual Desktop PC I had this issue, then when turning off the mod, the timer was also gone.
but now I tried it on my Work Laptop and I dont have this issue, but I also dont have the same mod combination as at home...

**Comment by ZiLko** [comment]
i dont think this has anything to do with xdbot u probably just have a platformer time mod
