### ISSUE TITLE
4K rendering and fix shader

### ISSUE THREAD

**Issue by TheUniverseIsKing** [ZiLko/xdBot#215]
Is it normal that if you render in 1440p / 4K or higher and enable fix shader the final rendered video is blocked at 1836 x 1034.. is it showing this cuz the geometry dash shaders are this resolution but the video is still in HD or 4K quality?

**Comment by ZiLko** [comment]
Ye its normal thats why if you have fix shaders enabled it doesnt let you change the resolution
