### ISSUE TITLE
Playing macro with a dual icon

### ISSUE THREAD

**Issue by Foxiseminger** [ZiLko/xdBot#217]
p2 just spins at the top of the screen (tested on the ultimate phase)
@ZiLko

**Comment by ZiLko** [comment]
already fixed but since it was a saving bug some macros broke, send me the macro so i can fix it

**Comment by Foxiseminger** [comment]
[The Ultimate Phase.gdr.json](https://github.com/user-attachments/files/17264394/The.Ultimate.Phase.gdr.json)

**Comment by Foxiseminger** [comment]
here

**Comment by ZiLko** [comment]
[The Ultimate Phase Fix.gdr.json](https://github.com/user-attachments/files/17264566/The.Ultimate.Phase.Fix.gdr.json)

**Comment by FoxyWorld1** [comment]
> [The Ultimate Phase Fix.gdr.json](https://github.com/user-attachments/files/17264566/The.Ultimate.Phase.Fix.gdr.json)
> 
> 

Thanks!
