### ISSUE TITLE
Cant click "Load" on saved macros

### ISSUE THREAD

**Issue by gorillaglue44** [ZiLko/xdBot#218]
90% of the time you literally just cant click it, this is very very annoying and i just wanna finish where i left off :(

**Comment by ZiLko** [comment]
do u have text select mod

**Comment by gorillaglue44** [comment]
yes, but, i recieve this bug with and without it, my theory is its trying to scroll even though i didnt hold

**Comment by ZiLko** [comment]
fake its text select try uninstalling it

**Comment by gorillaglue44** [comment]
im so confused now
THAT DIDNT WORK LAST TIME
WHY IS IT WORKING NOW
you transcended reality

**Comment by ZiLko** [comment]
i have transcended reality
