### ISSUE TITLE
Level with shaders rendering error

### ISSUE THREAD

**Issue by XBOCTATUK** [ZiLko/xdBot#219]
I was recording a Royal Roost Ruins level showcase, and when I looked at it, I saw artifacts, they seemed to be in places with shaders. This bug was both with and without "Fix shaders" enabled.

**Comment by ZiLko** [comment]
send screenshot

**Comment by XBOCTATUK** [comment]
![Screenshot_2024-10-05-19-31-47-628_video player videoplayer](https://github.com/user-attachments/assets/4b39bf86-7fda-440f-b2e9-c94316b606e6)
![Screenshot_2024-10-05-19-31-39-027_video player videoplayer](https://github.com/user-attachments/assets/bb439762-3581-4a02-a1d1-2ba38de92910)
![Screenshot_2024-10-05-19-31-31-853_video player videoplayer](https://github.com/user-attachments/assets/6fc7469f-0697-4f07-aacb-e8a66dfba1ea)
![Screenshot_2024-10-05-18-49-41-307_org telegram messenger](https://github.com/user-attachments/assets/645983bf-ccd3-4081-b8a5-977db39ba64a)
![Screenshot_2024-10-05-18-49-32-417_org telegram messenger](https://github.com/user-attachments/assets/466855b8-98da-4205-bf8f-3bf503eafd6f)
![Screenshot_2024-10-05-18-49-26-955_org telegram messenger](https://github.com/user-attachments/assets/eb7062d2-0b50-47b0-b10b-12627dc57174)
![Screenshot_2024-10-05-18-49-02-988_org telegram messenger](https://github.com/user-attachments/assets/39bf4764-6d46-4b67-9ec6-3157028f06d1)
![Screenshot_2024-10-05-18-48-38-670_org telegram messenger](https://github.com/user-attachments/assets/97a4de7e-3136-4f57-b3ac-bab660c85147)
![Screenshot_2024-10-05-18-48-11-750_org telegram messenger](https://github.com/user-attachments/assets/f1c7f555-78fd-4d6c-abfd-86de36d97606)

**Comment by ZiLko** [comment]
https://youtu.be/n-qGp_IKcOQ

dont resize the window while recording, but idk honestly, maybe its some weird args u have, or the ffmpeg you downloaded

**Comment by XBOCTATUK** [comment]
I didn’t change the screen resolution, I took the ffmpeg from the link that the mod itself offers, the arguments are standard (I only changed the output resolution and bitrate)

**Comment by XBOCTATUK** [comment]
This may have something to do with my laptop. I have an Intel Celeron with a built-in GPU, in theory, this can cause various artifacts
