### ISSUE TITLE
Crashes with Hide pause menu Hack

### ISSUE THREAD

**Issue by Kevadroz** [ZiLko/xdBot#22]
When showing the pause menu again in the other mod the game crashes, link to a relevant comment in the other mod's repo (the issue includes a crashlog): https://github.com/EKVgd/hidePauseMenuHack/issues/1#issuecomment-1934879533.

**Comment by esjdklhs** [comment]
same

**Comment by ZiLko** [comment]
hide pause menu hack issue

**Comment by EKVgd** [comment]
You sure? From what I can tell xdbot is just assuming a right menu bar exists in the pause menu. I can try to fix that in hide pause menu, but that would be way more effort than you adding one if statement in line 549 to fix that.

**Comment by EKVgd** [comment]
nvm don't bother with it I think I have found a way to fix it from my end. I will push an update later today.

**Comment by EKVgd** [comment]
fixed it.
