### ISSUE TITLE
Add enable or disable randomness

### ISSUE THREAD

**Issue by xHugoLA** [ZiLko/xdBot#226]
This helps in levels that have random paths or decorations, because if you have gameplay that changes with random trigger, the macro breaks, it would help a lot to be added in the next version

**Comment by ZiLko** [comment]
vro theres seed option :sob:

**Comment by ZiLko** [comment]
![image](https://github.com/user-attachments/assets/0e1b1822-81a8-4e21-b0d6-cff57ae626bf)
