### ISSUE TITLE
i make macros that look real because i have skill and i do you a favor (ill put my macros here) (MORE COMING SOON) tell me if there are bugs. also devs please make a discord so i can put my macros there and dont close this "issue"

### ISSUE THREAD

**Issue by idkrandomusercuz** [ZiLko/xdBot#227]
[Acu.gdr.json](https://github.com/user-attachments/files/17350864/Acu.gdr.json) (extreme demon)
[Bloodbath.gdr.json](https://github.com/user-attachments/files/17350865/Bloodbath.gdr.json) (extreme demon)
[Bloodlust.gdr.json](https://github.com/user-attachments/files/17350866/Bloodlust.gdr.json) (extreme demon)
[Falling Up.gdr.json](https://github.com/user-attachments/files/17350867/Falling.Up.gdr.json) (extreme demon)
[limbo but uwu ig idk (2).gdr.json](https://github.com/user-attachments/files/17350868/limbo.but.uwu.ig.idk.2.gdr.json) (insane) (but should be a demon)
[Nantendo.gdr.json](https://github.com/user-attachments/files/17350869/Nantendo.gdr.json) (medium demon)
[Next Cab Soon.gdr.json](https://github.com/user-attachments/files/17350871/Next.Cab.Soon.gdr.json) (easy demon)
[Ride.gdr.json](https://github.com/user-attachments/files/17350872/Ride.gdr.json) (medium demon)
[The Golden.gdr.json](https://github.com/user-attachments/files/17350873/The.Golden.gdr.json) (extreme demon)
[The Yangire.gdr.json](https://github.com/user-attachments/files/17350874/The.Yangire.gdr.json) (extreme demon)
[iSpyWithMyLittleEye.gdr.json](https://github.com/user-attachments/files/17350930/iSpyWithMyLittleEye.gdr.json) (easy demon)
[Metamorphosis.gdr.json](https://github.com/user-attachments/files/17350959/Metamorphosis.gdr.json) (medium demon)
[Sonic Wave.gdr.json](https://github.com/user-attachments/files/17351082/Sonic.Wave.gdr.json) (extreme demon)
[The Nightmare.gdr.json](https://github.com/user-attachments/files/17351099/The.Nightmare.gdr.json) (easy demon)
[Death Moon .gdr.json](https://github.com/user-attachments/files/17351121/Death.Moon.gdr.json) (easy demon)
[DeCode.gdr.json](https://github.com/user-attachments/files/17351132/DeCode.gdr.json) (easy demon)
[Slaughterhouse .gdr.json](https://github.com/user-attachments/files/17351158/Slaughterhouse.gdr.json) (extreme demon)
[Future Funk.gdr.json](https://github.com/user-attachments/files/17351175/Future.Funk.gdr.json) (hard demon)
[Change of Scene Imagination.gdr.json](https://github.com/user-attachments/files/17351231/Change.of.Scene.Imagination.gdr.json) (easy demon)
[Change of Scene No Imagination.gdr.json](https://github.com/user-attachments/files/17351233/Change.of.Scene.No.Imagination.gdr.json) (easy demon)

**Comment by ZiLko** [comment]
omw to close it

**Comment by idkrandomusercuz** [comment]
> https://discord.com/invite/H3vHJpz7Mj

dude i cant write in it

**Comment by idkrandomusercuz** [comment]
> omw to close it

can you make me a role like "macro maker" or something like that because im gonna make a lot of them (i take suggestions)

**Comment by ZiLko** [comment]
thats not my server lol

**Comment by idkrandomusercuz** [comment]
but if you do

**Comment by idkrandomusercuz** [comment]
wait why u close it i wanted people to access it
