### ISSUE TITLE
My macros randomly stopped working

### ISSUE THREAD

**Issue by Free544** [ZiLko/xdBot#231]
When I first recorded the macro it was working perfectly fine but after a few days the same macro stopped working and glitches on dual parts of a level. It happens with other levels with dual gameplay too. Please help me

**Comment by Free544** [comment]
[Sakupen Circles.gdr.json](https://github.com/user-attachments/files/17395535/Sakupen.Circles.gdr.json)
[Silent Circles Nerf 100.gdr.json](https://github.com/user-attachments/files/17395537/Silent.Circles.Nerf.100.gdr.json)

**Comment by ZiLko** [comment]
[Sakupen Circles Fix 1.gdr.json](https://github.com/user-attachments/files/17402601/Sakupen.Circles.Fix.1.gdr.json)
[Silent Circles Nerf Fix 1.gdr.json](https://github.com/user-attachments/files/17402602/Silent.Circles.Nerf.Fix.1.gdr.json)

**Comment by Free544** [comment]
Thank you so much for helping me!

**Comment by Free544** [comment]
It actually works now.. Thank you!
