### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by DrodedGd** [ZiLko/xdBot#233]
Android 64/32 idk.Ever since I installed the latest xdbot update on geode anytime I try loading a macro it plays for like one sec and my geode crashes never happened until now when I installed the latest upd if u see this pls can u help?

**Comment by CoderMonkey1956** [comment]
Try updating to latest version, zilko might have fixed this

**Comment by CoderMonkey1956** [comment]
From the changelog: "Fixed crash if some macro info was null for whatever reason."

**Comment by ZiLko** [comment]
no that was when loading idk why it crashes for this boi

> From the changelog: "Fixed crash if some macro info was null for whatever reason."

**Comment by CoderMonkey1956** [comment]
> no that was when loading idk why it crashes for this boi
> 
> > From the changelog: "Fixed crash if some macro info was null for whatever reason."

Ah ok

**Comment by DrodedGd** [comment]
Also I had to install the beta 6 version to be able to use macros bc beta 7 kept crashing since that was were the problems started

**Comment by ZiLko** [comment]
why tf u in beta 7 vro just update to 2.0.3
