### ISSUE TITLE
Render wave trail bug

### ISSUE THREAD

**Issue by Rexiyll** [ZiLko/xdBot#234]
When i try to render my replays, the wave trails act like a wave on d-blocked slopes. idk what to do

https://github.com/user-attachments/assets/ff7ac93a-8a1b-4c35-a9ab-2e4e1bd143ec

**Comment by ZiLko** [comment]
what mods do you have installed, full list

it seems like your game is completely skipping some clicks which doesnt happen normally

**Comment by ZiLko** [comment]
nvm i didnt see youre rendering

still send full mod list

**Comment by Rexiyll** [comment]
![image](https://github.com/user-attachments/assets/02c63e31-349c-46ab-bf2c-bd840ec7fbaf)
![image](https://github.com/user-attachments/assets/593a646e-219c-4fd4-8a76-c71b07eb2adb)
![image](https://github.com/user-attachments/assets/a25f0149-5599-43f6-aead-41dbcafa0b65)
![image](https://github.com/user-attachments/assets/d144768e-fdf2-4b4f-b566-9337c85fe999)
![image](https://github.com/user-attachments/assets/b8cbdd15-b408-4c8a-b9cd-e6a4d6fd1205)
i tried updating my ffmpeg but that also didnt work

**Comment by Rexiyll** [comment]
thx

**Comment by Rexiyll** [comment]
I found out that it was cbf's fault thank alot

**Comment by Rexiyll** [comment]
> > thx
> 
> And if It isn't a xdbot issue, start enabling mods a few at a time, then when it breaks again, do the same to that group you just enabled, and eventually figure out which mod is causing it

it was cbf thanks!!!

**Comment by ZiLko** [comment]
> I found out that it was cbf's fault thank alot

vro what you cant even use cbf with xdbot
