### ISSUE TITLE
My game is crashing

### ISSUE THREAD

**Issue by Asdjdofoi** [ZiLko/xdBot#238]
I just click to load my macros and my game crashed
2024-10-30T17:09:42+0700
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v3.8.1
Loader Commit: 47e0ca5
Bindings Commit: 7fbb83d
Installed mods: 18
Problems: 0

== Exception Information ==
C++ Exception: class nlohmann::json_abi_v3_11_3::detail::type_error("[json.exception.type_error.302] type must be number, but is null")
Faulty Mod: xdBot v2.0.0-beta.7 (zilko.xdbot)
Crashed thread: Main

== Stack Trace ==
 - C:\Windows\System32\KERNELBASE.dll + 2cd29 (RaiseException + 105)
 - C:\Windows\SYSTEM32\VCRUNTIME140.dll + 5267 (CxxThrowException + 151)
 - C:\Users\Professional\Desktop\Geometry Dash\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 1543ee
 - C:\Users\Professional\Desktop\Geometry Dash\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 13f188
 - C:\Users\Professional\Desktop\Geometry Dash\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 13ca2c
 - C:\Users\Professional\Desktop\Geometry Dash\libcocos2d.dll + 597cf (cocos2d::CCMenuItem::activate + 47)
 - 000001D22F150882 (Hook handler)
 - C:\Users\Professional\Desktop\Geometry Dash\Geode.dll + 45725 (geode::modifier::AsStaticFunction_activate<hook7<(anonymous namespace)::hook7Parent>,void (hook7<(anonymous namespace)::hook7Parent>::*)()>::Impl<void (hook7<(anonymous namespace)::hook7Parent>::*)()>::function + 21 | /home/runner/work/geode/geode/build/bindings/bindings/Geode/modify/CCMenuItem.hpp:35)
 - 000001D22F150882 (Hook handler)
 - C:\Users\Professional\Desktop\Geometry Dash\libcocos2d.dll + 58798 (cocos2d::CCMenu::ccTouchEnded + 40)
 - 000001D22F150C82 (Hook handler)
 - C:\Users\Professional\Desktop\Geometry Dash\Geode.dll + 45def (geode::modifier::AsStaticFunction_ccTouchEnded<hook15<(anonymous namespace)::hook15Parent>,void (hook15<(anonymous namespace)::hook15Parent>::*)(cocos2d::CCTouch *, cocos2d::CCEvent *)>::Impl<void (hook15<(anonymous namespace)::hook15Parent>::*)(cocos2d::CCTouch *, cocos2d::CCEvent *)>::function + 47 | /home/runner/work/geode/geode/build/bindings/bindings/Geode/modify/CCMenu.hpp:105)
 - 000001D22F150C82 (Hook handler)
 - C:\Users\Professional\Desktop\Geometry Dash\libcocos2d.dll + b0c3c (cocos2d::CCTouchDispatcher::touches + 444)
 - 000001D230D83882 (Hook handler)
 - C:\Users\Professional\Desktop\Geometry Dash\geode\unzipped\tobyadd.gdh\tobyadd.gdh.dll + 91ca8
 - 000001D230D83882 (Hook handler)
 - C:\Users\Professional\Desktop\Geometry Dash\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + 2daa76
 - 000001D230D83882 (Hook handler)
 - C:\Users\Professional\Desktop\Geometry Dash\libcocos2d.dll + 6b131 (cocos2d::CCEGLViewProtocol::handleTouchesEnd + 97)
 - C:\Users\Professional\Desktop\Geometry Dash\libcocos2d.dll + 76159 (cocos2d::CCEGLView::onGLFWMouseCallBack + 249)
 - 000001D230D8248B (Hook handler)
 - 000001D230D8248B (Hook handler)
 - C:\Users\Professional\Desktop\Geometry Dash\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + 1ab877
 - 000001D230D8248B (Hook handler)
 - C:\Users\Professional\Desktop\Geometry Dash\libcocos2d.dll + 76186
 - C:\Users\Professional\Desktop\Geometry Dash\libcocos2d.dll + d686b
 - C:\Windows\System32\USER32.dll + e858
 - C:\Windows\System32\USER32.dll + e4ee (CallWindowProcW + 142)
 - C:\Windows\SYSTEM32\OPENGL32.dll + 402a0
 - C:\Windows\System32\USER32.dll + e858
 - C:\Windows\System32\USER32.dll + e299
 - C:\Users\Professional\Desktop\Geometry Dash\libcocos2d.dll + d4198
 - C:\Users\Professional\Desktop\Geometry Dash\libcocos2d.dll + 72ca6 (cocos2d::CCApplication::run + 1078)
 - C:\Users\Professional\Desktop\Geometry Dash\GeometryDash.exe + 4a2d69
 - C:\Users\Professional\Desktop\Geometry Dash\Geode.dll + 2910da (gdMainHook + 554 | /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:181)
 - C:\Users\Professional\Desktop\Geometry Dash\GeometryDash.exe + 4a415a
 - C:\Windows\System32\KERNEL32.DLL + 17034 (BaseThreadInitThunk + 20)
 - C:\Windows\SYSTEM32\ntdll.dll + 526a1 (RtlUserThreadStart + 33)

== Register States ==
RAX: 00000000000003ff
RBX: 0000000000000000
RCX: 000001d23e6fd020
RDX: 0000000000000010
RBP: 0000000000000000
RSP: 00000012d833fe60
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00007ffd44fc26a1
R8:  0000000000022010
R9:  540be40000000002
R10: 00000000a40004a0
R11: 0000000000000000
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
x | [v1.0.5] alphalaneous.editortab_api
  | [v1.6.1] alphalaneous.happy_textures
  | [v1.8.3] beat.click-sound
x | [v1.6.2] dankmeme.globed2
x | [v1.0.0-beta.3] eclipse.eclipse-menu
x | [v1.0.1] fig.authentication
x | [v1.3.1] firee.object-workshop
x | [v1.9.0] geode.custom-keybinds
x | [v3.8.1] geode.loader
x | [v1.15.0] geode.node-ids
x | [v1.6.2] geode.texture-loader
x | [v1.0.0-alpha.2] sabe.persistenceapi
x | [v1.0.1-alpha.3] sabe.platformersaves
x | [v4.7.7] tobyadd.gdh
x | [v1.6.0-prerelease.2] uproxide.more_difficulties
x | [v1.3.4] uproxide.textures
  | [v1.0.4] weebify.congregation_jumpscare
x | [v2.0.0-beta.7] zilko.xdbot

**Comment by Asdjdofoi** [comment]
why help

**Comment by ZiLko** [comment]
did u modify the macro or is it from a different bot

send the macro here

**Comment by ZiLko** [comment]
hopefuly fxed

**Comment by Asdjdofoi** [comment]
> вы изменили макрос или он от другого бота
> 
> отправьте макрос сюда
[tidal wave.mhr (1).json](https://github.com/user-attachments/files/17584676/tidal.wave.mhr.1.json)
and
[Limbo.mhr.json](https://github.com/user-attachments/files/17584677/Limbo.mhr.json)

**Comment by Asdjdofoi** [comment]
> hopefuly fxed

oh yes
its just bad macro
