### ISSUE TITLE
I cant change the FPS cap to be 240fps

### ISSUE THREAD

**Issue by AvocaDoEe** [ZiLko/xdBot#240]
Exactly what the title says.
Changing the resolution works, but I tried changing the default 60fps to 240fps and it doesn't let me.
I even tried to do it by changing the actual 'saved.json' file from 60 to 240 for the render fps, but it just resets back to 60 every time I restart GD.

**Comment by CoderMonkey1956** [comment]
#232

**Comment by CoderMonkey1956** [comment]
> Exactly what the title says. Changing the resolution works, but I tried changing the default 60fps to 240fps and it doesn't let me. I even tried to do it by changing the actual 'saved.json' file from 60 to 240 for the render fps, but it just resets back to 60 every time I restart GD.

Just checked, the limit seems to be uncapped in the latest version on GitHub.

**Comment by AvocaDoEe** [comment]
I managed to get a 120fps recording working by adding (-r 120) to the "Extra Args:" section, but without that, it would still cap to 60fps. I'm on the latest version 'v2.0.0 real'.

Is there anywhere I have to click to uncap it or it it just default? The default came out to be 60 for me.

**Comment by ZiLko** [comment]
my bad

**Comment by ZiLko** [comment]
check 2..01

**Comment by ZiLko** [comment]
remove the extra args
