### ISSUE TITLE
Internal recorder does not reset the level when pressing ‘Start’.

### ISSUE THREAD

**Issue by sergiohzph** [ZiLko/xdBot#242]
For some unknown reason, recording the level with the internal recorder no longer restarts the progress of the level when the ‘Start’ button is pressed. This means that the final video does not start from the beginning, is there any way to correct this?

PS: Is there a Discord server for xdBot? I don't think the repository of this project is the right place to ask questions about how it works, as I don't think it's a bug, or maybe it is since it got updated a day ago, and since then, the video recording doesn't work properly as it used to.

**Comment by uHioVK** [comment]
just manually restart the level would be ok
I usually exit to the level info page before I start recording, then pause before the first attempt starts
