### ISSUE TITLE
Suggestion, not very hard to make I believe

### ISSUE THREAD

**Issue by AstroStuff** [ZiLko/xdBot#245]
Could you please make option that trajectory could be displayed for both sides in platformer? It would help bot levels a lot I believe.

**Comment by CoderMonkey1956** [comment]
This sounds cool. Could possibly be pretty laggy on some levels/depending on game mode tho.

**Comment by RaptorGaming28** [comment]
sounds great although it would definitely lagged a lot on low end devices since the original optimized trajectory is doubled

**Comment by ZiLko** [comment]
added

**Comment by CoderMonkey1956** [comment]
> added

sweet
