### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by yetyetty1234567890** [ZiLko/xdBot#246]
Can you add a way to toggle the checkpoint fix? (the problem is that it stops you from moving until you repress a button which isnt very good for optimized tasing)

**Comment by yetyetty1234567890** [comment]
also ig make the clickbot not pause the game every time you click

**Comment by yetyetty1234567890** [comment]
the fix is the one in beta-5

**Comment by ZiLko** [comment]
Clickbot doesnt pause the game every time you click
Checkpoint respawning doesnt stop you when respawning
Why tf are you in beta 5
