### ISSUE TITLE
[Suggestion] Auto use layout mode when recording audio

### ISSUE THREAD

**Issue by uHioVK** [ZiLko/xdBot#247]
Enable it to avoid lag on low end devices, or the audio (mainly SFXs and song clippings) may not be correctly synced.

**Comment by ZiLko** [comment]
get beter pc

**Comment by uHioVK** [comment]
ok I just worried too much

**Comment by CoderMonkey1956** [comment]
> ok I just worried too much

You can also download qolmod to use show layout

**Comment by ZiLko** [comment]
> > ok I just worried too much
> 
> You can also download qolmod to use show layout

same issue as xdbot show layout, you need to reload the level

**Comment by CoderMonkey1956** [comment]
> > > ok I just worried too much
> > 
> > 
> > You can also download qolmod to use show layout
> 
> same issue as xdbot show layout, you need to reload the level

Yeah? Isn't that normal for show layout mods

**Comment by ZiLko** [comment]
> > > > ok I just worried too much
> > > 
> > > 
> > > You can also download qolmod to use show layout
> > 
> > same issue as xdbot show layout, you need to reload the level
> 
> Yeah? Isn't that normal for show layout mods

yes but like i have to make u exit the level then open it again and then record audio so like 🥱🥱🥱🥱🥱

**Comment by CoderMonkey1956** [comment]
> > > > > ok I just worried too much
> > > > 
> > > > 
> > > > You can also download qolmod to use show layout
> > > 
> > > 
> > > same issue as xdbot show layout, you need to reload the level
> > 
> > 
> > Yeah? Isn't that normal for show layout mods
> 
> yes but like i have to make u exit the level then open it again and then record audio so like 🥱🥱🥱🥱🥱

Fair
