### ISSUE TITLE
[Suggestion but I be more clear this time]

### ISSUE THREAD

**Issue by yetyetty1234567890** [ZiLko/xdBot#248]
When you place a checkpoint while holding a button, if you restart back to that checkpoint, the button will release and therefore you will have to press that button again, and you can't hold it into the respawn. So what I am proposing is to make a toggle for the checkpoint fix in 2.0-beta.5, where this bug in the fix for the bug was added.

**Comment by ZiLko** [comment]
beta 5 was a bug
