### ISSUE TITLE
How I do tps or fps bypass

### ISSUE THREAD

**Issue by Lamratdeptrai** [ZiLko/xdBot#249]
Xdbot has now blocked all of the tps or fps bypass so I can't bot ILL level. Please!

**Comment by ZiLko** [comment]
you dont

**Comment by uHioVK** [comment]
curious about the reason, does pactice fixes or something else break when using fps values other than 240?

**Comment by ZiLko** [comment]
everything breaks on tps other than 240 cus i have to make it compatible and im too noob for that plus i have the feeling lots of stuff would break and i just cant be bothered
