### ISSUE TITLE
Macros breaking and inaccurate

### ISSUE THREAD

**Issue by Nowthiscomesfrominside** [ZiLko/xdBot#250]
Previously I have botted my own buffed version of death corridor and it worked completely fine, but when I play that macro now it doesn't work, and so far older versions or newer versions don't help, how do I fix this issue?

Now for inaccuracy, I can bot something in practice mode 354 times, but each time I separately record a macro, it dies either at that same spot, or somewhere else, I swear this is actually so frustrating.
Idk if it's because I'm not using 2.207 but this makes me wanna kms.

**Comment by uHioVK** [comment]
> ...now it doesn't work
does it become inaccurate or it doesn't play at all?

**Comment by ZiLko** [comment]
if it dies in a dual its a beta 3 bug that got fixed

**Comment by Nowthiscomesfrominside** [comment]
> > ...now it doesn't work
> 
> does it become inaccurate or it doesn't play at all?

Inaccurate, it just dies at random spots, and if I bot it again, it's still inaccurate and dies, either xdbot is breaking or my macros are breaking.

**Comment by Nowthiscomesfrominside** [comment]
Really embarrassing but I just found out that I have been using 360 TPS on eclipse menu omg so sorry

**Comment by CoderMonkey1956** [comment]
> Really embarrassing but I just found out that I have been using 360 TPS on eclipse menu omg so sorry

Happened to me to a while ago lol 😂 it's ok
