### ISSUE TITLE
Macro editor UI moving away

### ISSUE THREAD

**Issue by uHioVK** [ZiLko/xdBot#251]
![image](https://github.com/user-attachments/assets/caaae074-4db5-4cfc-8d3a-a70d2223d880)
if you keep clicking turn page button it'll move out of the screen

**Comment by RaptorGaming28** [comment]
it's actually quite funny ngl

**Comment by 7hat3eird0ne** [comment]
will this get fixed soon? it makes adding any inputs outside of first page impossible :(

**Comment by ZiLko** [comment]
fix
