### ISSUE TITLE
Fade in / out when rendering

### ISSUE THREAD

**Issue by AtlaszFox** [ZiLko/xdBot#258]
It'd be nice to have a built in fade in and out for renders, with the fade in being the same as the one the game does when opening a level. This would be useful for showcasing levels, since some creators choose to put art and similar stuff before the start of a level, which often goes unseen in showcases (pictured is Future Funk II)
![image](https://github.com/user-attachments/assets/140f85ee-f2ea-436b-961e-3f4e1e3fc26e)

**Comment by ZiLko** [comment]
i added fade in and fade out but it doesnt freeze the screen like the one that happens when you open a level
