### ISSUE TITLE
Macro settings button is completely gone.

### ISSUE THREAD

**Issue by madeline-yana** [ZiLko/xdBot#260]
<img width="501" alt="{A3D5767C-8289-4684-A42E-8E571BC3A7C6}" src="https://github.com/user-attachments/assets/39253d04-47ff-44dd-af50-f02c960d8dcd">
<img width="223" alt="{507FA431-EA5D-4F82-87CE-93BB58834FB3}" src="https://github.com/user-attachments/assets/1aeb56da-71ac-4923-b7c1-841cfb739a86">

**Comment by ZiLko** [comment]
u dumbass disabled it in settings

**Comment by ZiLko** [comment]
open the menu using the keybind and enable it again
