### ISSUE TITLE
Error when rendering levels with Audio Triggers

### ISSUE THREAD

**Issue by Peppino16** [ZiLko/xdBot#261]
![Geometry Dash Screenshot 2024 11 27 - 19 16 22 07](https://github.com/user-attachments/assets/40aa4fb6-0b67-44ff-9996-3439fc616964)

Audio starts immediately even though it is deactivated by the triggers for the first few seconds and only starts from the 3rd trigger

https://github.com/user-attachments/assets/50b75d62-a616-4523-9f20-ca75e1e098ac

At the music drop you can see and hear the Shift in audio clearly.

Thats the level id : 107931617

**Comment by ZiLko** [comment]
are you using audio recordig

**Comment by ZiLko** [comment]
https://github.com/user-attachments/assets/2a5e6559-9eb6-4f9a-9a24-5a09ebe8c0c3

This is using audio recording
