### ISSUE TITLE
keyboard not working

### ISSUE THREAD

**Issue by jalapeno4** [ZiLko/xdBot#262]
IDk if its a problem on my part or a known problem but my keyboard doesnt work while using this mod, which makes it very hard to place checkpoints and i also usually play with space bar

**Comment by ZiLko** [comment]
Custom keybinds issue probably, not xdbot

**Comment by jalapeno4** [comment]
i dont have custom keybinds on is that another mod?

**Comment by ZiLko** [comment]
u cant even use xdbot without custom keybinds
