### ISSUE TITLE
Whenever render finishes it tellls me i have wrong render args

### ISSUE THREAD

**Issue by 7hat3eird0ne** [ZiLko/xdBot#265]
![obrazek](https://github.com/user-attachments/assets/eef3f7c9-852d-450d-9aea-33ab15973971)

i tried updating the ffmpeg and reseting settings to default, but it doesnt work

i tried to first do this with limbo, then i did this on a different level twice (one u see in screenshot), so it isnt just on the level side, neither of these levels use shaders

**Comment by ZiLko** [comment]
enable geode console and show error

**Comment by 7hat3eird0ne** [comment]
![obrazek](https://github.com/user-attachments/assets/479f6f28-9ebd-4c2a-9d54-4faab1213112)
here, im unsure if u need more i just screenshotted things in red, i tried to render the shorter level

srry for replying late btw

**Comment by ZiLko** [comment]
show me ur render width and height it says its 0 x 0

**Comment by 7hat3eird0ne** [comment]
![obrazek](https://github.com/user-attachments/assets/5968eb33-9a8f-41a3-8a2d-f53af5d099cc)
oh so i have this wrong? i didnt realise im stupid

**Comment by ZiLko** [comment]
what the fuck

uninstall betterinputs please

**Comment by 7hat3eird0ne** [comment]
i dont use betterinputs, i dont have it installed
![obrazek](https://github.com/user-attachments/assets/de47428a-c361-4968-98df-3ddce8812496)

i just enteterd in the values based of other post and nvidia codec and it worked thx for hsownig me the issue, idk why there were default values as 0.5 , even when i reinstalled xdbot (maybe if i reinstalled without og save data it would have correct values but idk)

**Comment by ZiLko** [comment]
what other mods do you have

betterinputs is the only mod i know causes all inputs to have the same text from speedhack

if you ever had betterinputs even once and uninstalled it then it might have done that to the values

**Comment by 7hat3eird0ne** [comment]
i used to have it, explains, thx
