### ISSUE TITLE
Recorder crashes if the path isn't found

### ISSUE THREAD

**Issue by M336G** [ZiLko/xdBot#273]
Would be cool if it were to show a message saying it cannot access the said path instead.

**Comment by ZiLko** [comment]
idk what you mean it shouldnt crash

**Comment by ZiLko** [comment]
vro what im literally creating the directory cus it doesnt exist thats why it says "create_directory"

**Comment by ZiLko** [comment]
this can only be replicated when u delete the folder so kinda ur fault fr

**Comment by ZiLko** [comment]
i mean i did check for the folders existence just not every other previous folder in the path which i would have to do to prevent crash
