### ISSUE TITLE
Follow trigger got mess up when timewrap activate during recording

### ISSUE THREAD

**Issue by albertkan1223** [ZiLko/xdBot#274]
https://github.com/user-attachments/assets/19be0a6f-8db6-4dcb-881d-29a813a264ef

It also gets recorded into the macro, which can be a massive issue for something like a custom gamemode icon or a background as example

**Comment by ZiLko** [comment]
send level

**Comment by albertkan1223** [comment]
113103338

**Comment by albertkan1223** [comment]
> send level

113103338
It only happens when timewrap set to a higher value than 1 btw

**Comment by ZiLko** [comment]
oo o i might know why it happesn and i am afraid fixing it would break every macro in timewarp

**Comment by albertkan1223** [comment]
> oo o i might know why it happesn and i am afraid fixing it would break every macro in timewarp

Is timewrap accidently multiplied follow trigger's attributes during the recording process?

**Comment by ZiLko** [comment]
fix
