### ISSUE TITLE
xdBot New Version

### ISSUE THREAD

**Issue by OMeguminO** [ZiLko/xdBot#279]
Hello there, I have tested the new boost audio rendering way, it seems to be a bit broken.
Rendering like before where it replays the level twice still happens, but the 2nd run where it records the audio for some reason takes really long to render as seen here: 
![grafik](https://github.com/user-attachments/assets/768e6a12-d746-4c9d-bba5-0ba199da39b4)
Overall the rendering takes longer once it's done. However the final render does look correct except for the fact that the fade out didn't work.

**Comment by OMeguminO** [comment]
The glitch where pulse objects become huge only happens on the audio run and are therfor only a visual bug

**Comment by OMeguminO** [comment]
The slower rendering is due to the fade in/fade out options

**Comment by ZiLko** [comment]
the big object pulsing thing is cus im forcing the games volume to the volume in render settings but it shouldnt affect the video
