### ISSUE TITLE
Error adding song

### ISSUE THREAD

**Issue by CatGirlCutie01** [ZiLko/xdBot#281]
I'm getting an error when trying to render a level. 
![image](https://github.com/user-attachments/assets/2d0ea060-6779-4c4a-8ac9-6d3b2c5d80c7)
here are my settings 
![image](https://github.com/user-attachments/assets/a19f611a-7c19-4fe1-a39b-ff750a862735)

**Comment by ZiLko** [comment]
try using "only add song"

**Comment by ZiLko** [comment]
or disable fade out

**Comment by CatGirlCutie01** [comment]
disabling fade out works, thank you
