### ISSUE TITLE
Add support for HEVC codecs

### ISSUE THREAD

**Issue by AtlaszFox** [ZiLko/xdBot#283]
Right now, you can render videos up to about 8K with xdbot, as long as you replace the codec with one that supports those resolutions.
The fade in and out options break this since this is technically not supported officially, re-encoding the video using .264 and promptly failing because of the resolution.

The fix for this is like, pretty simple so

**Comment by ZiLko** [comment]
o

**Comment by ZiLko** [comment]
i made it so it re encodes the video with the codec u used before
