### ISSUE TITLE
QOL Sudgesstion

### ISSUE THREAD

**Issue by yetyetty1234567890** [ZiLko/xdBot#285]
Add an option for mirror inputs where it will flip the other player's input (helps in silent circles) (TPS UNLOCKER)

**Comment by ZiLko** [comment]
already there

**Comment by yetyetty1234567890** [comment]
> already there

Where?

**Comment by ZiLko** [comment]
last page

**Comment by ZiLko** [comment]
not tps bypass i mean mirror inputs
