### ISSUE TITLE
Layout mode Problem

### ISSUE THREAD

**Issue by AhhhhhWasTaken** [ZiLko/xdBot#286]
When I use layout mode on geode the 2.0 teleport portals are disabled making some levels not work. Please fix.

**Comment by ZiLko** [comment]
![image](https://github.com/user-attachments/assets/6a5e83d6-9e66-4d98-9e9a-8411773fb0d2)

**Comment by ZiLko** [comment]
portals are there what do you mean

**Comment by ZiLko** [comment]
fixed on 2.2.2

**Comment by AhhhhhWasTaken** [comment]
Cool
