### ISSUE TITLE
xdBot Crashing the game after recording

### ISSUE THREAD

**Issue by OMeguminO** [ZiLko/xdBot#287]
Crash log listed below, also made a short youtube video to show the issue:

This didn't happen with xdBot Version 2.2.1
https://youtu.be/taH5FJJLQp0

2024-12-19T03:14:37+0100
Whoopsies! An unhandled exception has occurred.
It appears that the crash occurred while executing code from the "zilko.xdbot" mod. Please submit this crash report to its developers (Zilko) for assistance.

== Geode Information ==
Loader Version: v4.1.0
Loader Commit: 695f39f
Bindings Commit: 16df0dd
Installed mods: 36
Outdated mods: 3
Problems: 0

== Exception Information ==
Faulty Module: E:\Games\Steam\steamapps\common\Geometry Dash\geode\unzipped\zilko.xdbot\zilko.xdbot.dll
Faulty Mod: xdBot v2.2.2 (zilko.xdbot)
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 00007FFA8779673F (zilko.xdbot.dll + 7673f)
Number Parameters: 2
Crashed thread: Main

== Stack Trace ==
 - E:\Games\Steam\steamapps\common\Geometry Dash\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 7673f
 - 0000021253451882 (Hook handler)
 - E:\Games\Steam\steamapps\common\Geometry Dash\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 137aa1
 - E:\Games\Steam\steamapps\common\Geometry Dash\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 62ddb
 - 0000021253451882 (Hook handler)
 - E:\Games\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 250294
 - 0000021253453082 (Hook handler)
 - E:\Games\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.node-ids\geode.node-ids.dll + a30fa
 - E:\Games\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.node-ids\geode.node-ids.dll + 375d5
 - 0000021253453082 (Hook handler)
 - E:\Games\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 395945
 - E:\Games\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 2f808 (cocos2d::CCCallFunc::execute + 24)
 - E:\Games\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 36c41 (cocos2d::CCSequence::update + 257)
 - E:\Games\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 3832e (cocos2d::CCActionManager::update + 142)
 - E:\Games\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + c06dd (cocos2d::CCScheduler::update + 93)
 - 0000021252784882 (Hook handler)
 - 0000021252784882 (Hook handler)
 - 0000021252784882 (Hook handler)
 - 0000021252784882 (Hook handler)
 - 0000021252784882 (Hook handler)
 - 0000021252784882 (Hook handler)
 - E:\Games\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + bbf14 (cocos2d::CCDirector::drawScene + 36)
 - 000002125CAD4C82 (Hook handler)
 - 000002125CAD4C82 (Hook handler)
 - E:\Games\Steam\steamapps\common\Geometry Dash\geode\unzipped\absolllute.megahack\absolllute.megahack.dll + 168c58
 - 000002125CAD4C82 (Hook handler)
 - E:\Games\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + bc62b
 - E:\Games\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 72c42 (cocos2d::CCApplication::run + 1122)
 - E:\Games\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4b6e32
 - E:\Games\Steam\steamapps\common\Geometry Dash\Geode.dll + 24359d (gdMainHook + 557 | /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:181)
 - E:\Games\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4b821a
 - C:\Windows\System32\KERNEL32.DLL + 1259d (BaseThreadInitThunk + 29)
 - C:\Windows\SYSTEM32\ntdll.dll + 5af38 (RtlUserThreadStart + 40)

== Register States ==
RAX: 0000000000000000
RBX: 0000000000000000
RCX: 000002124f340000
RDX: 000002124f340000
RBP: 0000000000000000
RSP: 000000daae35f8d0
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00007ffb4a60af38
R8:  000002124f443a80
R9:  0000000000000001
R10: 0000000000000003
R11: 000000daae35df90
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
x | [v8.0.5-alpha.2] absolllute.megahack
x | [v1.0.7] alphalaneous.awesome_modifier_icons
x | [v1.7.3] alphalaneous.happy_textures
x | [v1.0.9] alphalaneous.improved_group_view
x | [v1.0.12] alphalaneous.improvedlink
x | [v1.2.11] alphalaneous.projectedstars
x | [v1.0.8] cdc.level_thumbnails
x | [v4.3.1] cvolton.betterinfo
x | [v1.1.0] cvolton.level-id-api
x | [v1.3.1] cvolton.misc_bugfixes
x | [v2.4.3] elohmrow.death_tracker
  | [v1.1.2] firee.overchargedlevels
* | [v0.3.2] flafy.autonong
x | [v3.0.1] fleym.nongd
x | [v1.10.1] geode.custom-keybinds
x | [v4.1.0] geode.loader
x | [v1.18.0] geode.node-ids
  | [v1.6.7] geode.texture-loader
x | [v1.3.1] grian.art_importer
x | [v1.7.2] hiimjustin000.integrated_demonlist
x | [v1.2.0] hjfod.backups
x | [v6.10.0-alpha.3] hjfod.betteredit
x | [v1.4.1] hjfod.gdshare
x | [v1.4.1] hjfod.gmd-api
x | [v1.2.1] hjfod.quick-volume-controls
x | [v1.1.0] hjfod.trashcan
* | [v1.2.0] itzkiba.grandpa_demon
x | [v1.2.3] mat.run-info
x | [v1.0.0-beta.47] minemaker0430.gddp_integration
x | [v1.4.2] nytelyte.wave_trail_drag_fix
* | [v0.8.0-beta.1] peony.silicate
  | [v1.0.0-beta.1] rainixgd.geome3dash
x | [v3.1.0] spaghettdev.gd-roulette
x | [v3.0.1] techstudent10.discord_rich_presence
  | [v1.3.5] uproxide.textures
x | [v2.2.2] zilko.xdbot

**Comment by ZiLko** [comment]
fix

**Comment by OMeguminO** [comment]
Can confirm it is fixed, thank you
