### ISSUE TITLE
Touch triggers not working

### ISSUE THREAD

**Issue by Sergey0819** [ZiLko/xdBot#291]
Touch triggers don't work when macro is enabled

Video with issue: https://drive.google.com/file/d/1CCWNmz3QWuZAn14XYBkyho0JTCzv_dAJ/view?usp=drive_link

**Comment by ZiLko** [comment]
send level

**Comment by Sergey0819** [comment]
one sec

**Comment by Sergey0819** [comment]
113357022

> send level

**Comment by ZiLko** [comment]
it doesnt even work normally

**Comment by ZiLko** [comment]
![image](https://github.com/user-attachments/assets/3a4f4a79-2ae3-457d-b4c1-ac418f34f004)

**Comment by ZiLko** [comment]
cant go up in vanilla

**Comment by ZiLko** [comment]
send fixed version

**Comment by Sergey0819** [comment]
> it doesnt even work normally

what exactly

**Comment by ZiLko** [comment]
cant go up and im in vanilla gd

**Comment by Sergey0819** [comment]
> cant go up and im in vanilla gd

idk, but everything works for me
