### ISSUE TITLE
Click between frames

### ISSUE THREAD

**Issue by hexz347** [ZiLko/xdBot#292]
I have 60fps, which is a low framerate and i love your bot but would like to use CBF and xdBot at the sametime. Could you tell me why cbf is incompatible and please add CBF support if possible.

Have a great day

**Comment by ZiLko** [comment]
xdbot relies on how inputs work and cbf changes completely how inputs work

**Comment by hexz347** [comment]
Ok thanks

**Comment by CoderMonkey1956** [comment]
@hexz347 if you're not on windows than you can try using click on steps, that might be incompatible tho

**Comment by ZiLko** [comment]
i am not adding cbf support

**Comment by CoderMonkey1956** [comment]
> i am not adding cbf support

Yea I think the cbf dev is planning to make it work with bots anyways
