### ISSUE TITLE
Suggestion: Add a proper .xd file extension loader

### ISSUE THREAD

**Issue by Meandtheboeings8** [ZiLko/xdBot#294]
Add an .xd file extension loader that renders fps and coordinates in .xd files extension so that there's no trouble replaying it

**Comment by ZiLko** [comment]
its already as proper as it can be

**Comment by CoderMonkey1956** [comment]
The .gdr file extension was added on August 19th, 2024. That was 135 days ago (158 days into the mods life as of today). XDBot hit it's all time peak on search terms on August 18-24, 2024. Safe to say most users are recording in .gdr.
