### ISSUE TITLE
Can't find "Enable Clickbot" anywhere

### ISSUE THREAD

**Issue by OrangeSoulakaBravery** [ZiLko/xdBot#297]
There's no keybind for it, no check i can check to enable it, this mod promised a clickbot. Where is it?

**Comment by ZiLko** [comment]
![image](https://github.com/user-attachments/assets/e59ce59d-b6bf-413a-95c6-633e6c78b5b4)
![image](https://github.com/user-attachments/assets/8f7f3454-7c50-47c5-b50c-7aa85c47fbb7)
![image](https://github.com/user-attachments/assets/e28e243f-29fe-4dab-9d9b-6040d9f42fb4)
![image](https://github.com/user-attachments/assets/4e428e7b-88e8-48e5-be4d-94794d8e9306)
![image](https://github.com/user-attachments/assets/d4d904b3-43e0-4c06-9180-08f0ecdf484c)

**Comment by OrangeSoulakaBravery** [comment]
where is this?

**Comment by OrangeSoulakaBravery** [comment]
nvm

**Comment by OrangeSoulakaBravery** [comment]
close this
