### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by LegoboyN12** [ZiLko/xdBot#3]
maybe?

**Comment by ZiLko** [comment]
I don't have a mac so i can't test, but if you have a mac and you want to help test, you can drop your discord here so i can contact you if i ever make a mac version

**Comment by ZairuFujimoto** [comment]
Bro, try making a frame correction mod like the megahacks mod

**Comment by ZairuFujimoto** [comment]
Bro, try making a frame correction mod like the megahacks mod

**Comment by ZairuFujimoto** [comment]
Fixed lags while recording and playing levels with many objects

**Comment by ZairuFujimoto** [comment]
Fixed lags while recording and playing levels with many objects

**Comment by Letsygo** [comment]
> I don't have a mac so i can't test, but if you have a mac and you want to help test, you can drop your discord here so i can contact you if i ever make a mac version

Id be happy to test
