### ISSUE TITLE
unable to load the dll (error_proc_not_found)

### ISSUE THREAD

**Issue by risugop** [ZiLko/xdBot#32]
i installed xdbot from geode and every time i open gd the game says that the xdbot is trying to access a funcion defined in other dll, i tried reinstalling the mod and geode itself but the error keeps happening
![huh](https://github.com/ZiLko/xdBot/assets/160103267/690d70f7-d870-4ebd-aef4-2b852378b5f1)

**Comment by ZiLko** [comment]
Update Geode Manually.
