### ISSUE TITLE
AUTO SAFE MODE DOSENT WORK

### ISSUE THREAD

**Issue by asddsaco** [ZiLko/xdBot#37]
I ACCIDENTALLY COMPLETED SONIC WAVE BECAUSE THE AUTO SAFE MODE DIDNT WORK PLEASE HELP ME I NEED TO UNCOMPLETE SONIC WAVE

**Comment by ZiLko** [comment]
xd

**Comment by ZiLko** [comment]
safe mode works for me so skill issue ig
