### ISSUE TITLE
Problems with making macros

### ISSUE THREAD

**Issue by UnKombtr3D3Usuari0** [ZiLko/xdBot#38]
The bot stopped working and if I try to use frame Stepper it stops working and if I put a configuration and then apply it wants to change another configuration and if I hit apply the frame Stepper doesn't works
![IMG20240223195257](https://github.com/ZiLko/xdBot/assets/161104762/e930d845-da00-4be6-8239-102092079e33)

**Comment by ZiLko** [comment]
salida de emergencia
