### ISSUE TITLE
Game sometimes crashes when using quick restart keybinds in first few attempts while recording

### ISSUE THREAD

**Issue by zkayns** [ZiLko/xdBot#39]
![image](https://github.com/ZiLko/xdBot/assets/80561998/cf4fd5a4-6590-4ae9-91a2-05a42c56a3c9)

**Comment by zkayns** [comment]
[2024-02-24_23-05-25.log](https://github.com/ZiLko/xdBot/files/14395214/2024-02-24_23-05-25.log)

**Comment by Raptoxa** [comment]
I got the same problem...
[2024-03-02_18-45-13.log](https://github.com/ZiLko/xdBot/files/14470797/2024-03-02_18-45-13.log)

**Comment by Raptoxa** [comment]
for me it always occurs when making a macro after having previously created one

**Comment by zkayns** [comment]
> for me it always occurs when making a macro after having previously created one

ye same, it doesn't always happen on the second record tho. seems to be inconsistent
