### ISSUE TITLE
Not working and mobile support?

### ISSUE THREAD

**Issue by CatastrophicGD** [ZiLko/xdBot#4]
So im on mobile and i loaded the mod and it just doesnt work it says "there was an error loading a mod" or something like that (probaly because im on mobile) please add mobile support

**Comment by ZiLko** [comment]
WIll try but i haven't been able to compile a mobile mod yet

**Comment by CatastrophicGD** [comment]
Thanks!

**Comment by CatastrophicGD** [comment]
> WIll try but i haven't been able to compile a mobile mod yet
Thanks!

**Comment by ZiLko** [comment]
Mobile version in a day or two
