### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nivonclient** [ZiLko/xdBot#43]
[2024-02-28_18-43-00.log](https://github.com/ZiLko/xdBot/files/14433364/2024-02-28_18-43-00.log)

**Comment by RxAttacker** [comment]
make sure geode.node-ids is on, xdBot is unable to be used without Node-Ids. Also please provide more information that can help us fix this issue.

**Comment by nivonclient** [comment]
i dont know, but node-ids is on and somehow when i was trying to record things, thats was crash immediately infront of me

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.2
