### ISSUE TITLE
[Feature request] RNG manipulator

### ISSUE THREAD

**Issue by hello6798** [ZiLko/xdBot#45]
I propose the integration of an RNG manipulator as a key feature in xdBot, particularly beneficial for TASing levels that involve random elements. The RNG manipulator would essentially record and replicate the random triggers' outcomes during the TASing process, ensuring consistent results on replay.

**Comment by HumaanK** [comment]
aw this would be awesome

**Comment by Ant2718281828459045235360** [comment]
yoo that would be amazing

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.2
