### ISSUE TITLE
add various types of accuracies the bot can have

### ISSUE THREAD

**Issue by ItzFlowerGMD** [ZiLko/xdBot#5]
since "vanilla accuracy" (atleast how i call it) already exists,
i would consider adding "input fix" and a "frame fix" accuracy mode

"input fix" mode goes like this: every time the player does an input the position, velocity, speed, etc is saved in the macro so when the bot plays it back it forcefully puts the player in that position. this should improve accuracy by a lot.

"frame fix" is pretty much the same thing as "input fix" but instead of saving position, velocity, speed, etc only when the player does an input, it saves it in every frame. this should gurantee 100% accuracy. (this is also how omegaBot worked in 2.1)

**Comment by ZiLko** [comment]
ye i was gonna do that but i still gotta figure out how to xd

**Comment by ItzFlowerGMD** [comment]
> ye i was gonna do that but i still gotta figure out how to xd

oh ok lol

**Comment by ZiLko** [comment]
Will be adding this in the next 1 or 2 days

**Comment by ItzFlowerGMD** [comment]
> I suggest you save the x-pos, y-pos, rotation, etc... and force the game to use it.

thats literally what i said

**Comment by ZiLko** [comment]
Added on v1.3.0, will be on geode soon (hopefully)
