### ISSUE TITLE
EVERY SINGLE MACRO

### ISSUE THREAD

**Issue by AcePainiteGitHub** [ZiLko/xdBot#56]
every single macro I've collected has not been working correctly. This was not a problem 2 days ago. Is the buggy time involved?

**Comment by AcePainiteGitHub** [comment]
just found out the macro for previous versions broke because of the new update

**Comment by AcePainiteGitHub** [comment]
Good job Zilko, now YOU MADE ME HAVE TO RESTART MY MACRO COLLECTION

**Comment by ZiLko** [comment]
Skill issue im literally playing macros from the first ever xdBot version just fine 🥱

**Comment by ZiLko** [comment]
Send me a few macros that break for you
