### ISSUE TITLE
Please add mac support

### ISSUE THREAD

**Issue by FireDasher** [ZiLko/xdBot#57]
I use a mac, i don't have a windows or an android, and I have a youtube channel and i need content for it, and this mod would be great for youtube content.

Please try to add mac support, and if you need me to test your mod, i can join your discord or something just tell me the invite link on this post.

**Comment by Letsygo** [comment]
My channel is unpopular and with mac support for this mod i might be able to become more popular.
My channel: https://www.youtube.com/@Firedasher22
