### ISSUE TITLE
FIX THIS SHI GODDAMMIT 

### ISSUE THREAD

**Issue by Raptoxa** [ZiLko/xdBot#61]
https://github.com/ZiLko/xdBot/issues/39
https://github.com/ZiLko/xdBot/issues/39

**Comment by ZiLko** [comment]
vro its completely random i dont know how to fixxxx

i found a way to replicate a restart crash a while ago which i fixed but it seems to still be a thing just different steps

**Comment by Raptoxa** [comment]
aw man, i hope you find a fix someday, untill then we just have to live with it i guess
