### ISSUE TITLE
Bug That Been TOO BAD

### ISSUE THREAD

**Issue by nivonclient** [ZiLko/xdBot#66]
the macro get the bug like make the player teleport to somewhere or just 
![GeometryDash 2024-03-20 20-02-19-245](https://github.com/ZiLko/xdBot/assets/118033787/6ca194d1-04b3-41fa-88a3-74601ab1caa6)
![GeometryDash 2024-03-20 20-02-54-709](https://github.com/ZiLko/xdBot/assets/118033787/6ac180f5-e25c-40b0-baa3-020e81bbd153)

![GeometryDash 2024-03-20 20-02-46-325](https://github.com/ZiLko/xdBot/assets/118033787/53331c30-684c-409d-90f0-557dee86ddbf)

**Comment by nivonclient** [comment]
i think that may cause by the error new recording program

**Comment by ZiLko** [comment]
how did bro do that

**Comment by nivonclient** [comment]
your new recording program is the problem

**Comment by nivonclient** [comment]
> how did bro do that

your new recording program is the problem

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.2
