### ISSUE TITLE
inaccurate

### ISSUE THREAD

**Issue by AcePainiteGitHub** [ZiLko/xdBot#69]
This mod is getting borderline impossible to record a macro. In previous versions, I can just die a bunch of times in Slaughterhouse and still have an accurate macro. Current versions, die a few times, Macro becomes heavily inaccurate

**Comment by HumaanK** [comment]
With all due respect, I personally believe that this is your fault because you are the only person who can control the accuracy of YOUR OWN macro, not the mod. In conclusion, you yourself need to make the macro accurate.

**Comment by Bryandrr** [comment]
ive had a problem like this

**Comment by Ant2718281828459045235360** [comment]
same

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.2
