### ISSUE TITLE
A crash when I restart my level 

### ISSUE THREAD

**Issue by HXDdarkwolf** [ZiLko/xdBot#73]
This problem pops up when I restart my level with a key-bind for Mega Mack v8 Alpha 

Error Message:
![image](https://github.com/ZiLko/xdBot/assets/165345987/370c2154-b6ba-4f38-ab06-089cb5f33566)

Sorry i couldn't copy the message.

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.2
