### ISSUE TITLE
not appearing on geode??

### ISSUE THREAD

**Issue by HumaanK** [ZiLko/xdBot#78]
i tried everything i could, i searched every tab, put on all filters for all devices and no luck. anybody got suggestions?

(xdBot was one of the main reasons I got geode for so i really wanna get it)

edit: im also on linux (steamdeck) but it should still appear but it's not :/

**Comment by GeoGhast** [comment]
I regret having uninstalled xdbot, now I can't record my gameplay >:(

**Comment by GeoGhast** [comment]
PLS ADD IT TO GEODE AGAIN!!!!!

**Comment by HumaanK** [comment]
> PLS ADD IT TO GEODE AGAIN!!!!!

wait is it removed? i wont have time to check but if it is then that sucks real bad
