### ISSUE TITLE
Why is xdbot discontinued? 

### ISSUE THREAD

**Issue by ChumbleDev** [ZiLko/xdBot#79]
I’m curious to why it was discontinued and removed from geode entirely

**Comment by HumaanK** [comment]
If you're trying to install it while it's removed, the releases has a .geode file you can import into the geode mod folder. Hope I could help!

**Comment by ZslavxL** [comment]
> If you're trying to install it while it's removed, the releases has a .geode file you can import into the geode mod folder. Hope I could help!

how and where do i download the file lol

**Comment by ZslavxL** [comment]
> If you're trying to install it while it's removed, the releases has a .geode file you can import into the geode mod folder. Hope I could help!

NVM i found the file in the latest update, tysm for helping me, i really wanted to showcase my level!

**Comment by 3NEPTUNE3** [comment]
i also doesnt know why xdbot is deleted, and I tried hummanK's method and didn't worked it said it needs to download geode.node.ids

**Comment by Usarene** [comment]
THEN DOWNLOAD IT

**Comment by skshype** [comment]
well maybe he already has it downloaded we dont know
can u send a pic?

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.2
