### ISSUE TITLE
How to downloud

### ISSUE THREAD

**Issue by Jxrt2** [ZiLko/xdBot#82]
I dont know how to download the mega

**Comment by GennyGITGITHUB** [comment]
install geode (if you didnt already) it should be there if it isnt there just download the .geode file and replace it in Android > media > com.geode.launcher > game > geode > mods and there you go and hoped this helped!!

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.2
