### ISSUE TITLE
Wave trail doesn't work

### ISSUE THREAD

**Issue by MultipleGaming** [ZiLko/xdBot#85]
![image](https://github.com/ZiLko/xdBot/assets/149714515/e2599efb-229b-43b3-9e68-e51a77c0a80e)

**Comment by wrth875** [comment]
me too it happens also on openhack tho

**Comment by badre997** [comment]
how to fix??

**Comment by ZiLko** [comment]
https://github.com/ZiLko/xdBot/releases/tag/v2.0.0-alpha.2
