### ISSUE TITLE
Macro not working

### ISSUE THREAD

**Issue by totallynotreal** [ZiLko/xdBot#9]
I clicked the "record" tab, but when i complete the level in practice (also with the integrated speedhack) (dont know if both of these afect anything) i saved it afterwards, and when i clicked on the play tab, absolutely nothing happened ingame. am i missing something or doing something wrong?

**Comment by ZiLko** [comment]
Can you send a video of the steps please

**Comment by totallynotreal** [comment]
Im not sure on how to show it, since it works fine with shorter levels??? i tried in a level of mine thats like 3 mins long, does that have to do with anything???

**Comment by ZiLko** [comment]
Idk i havent seen anyone else get this bug, and it hasnt happened to me

**Comment by totallynotreal** [comment]
Hey, i got the reason why it happened: apparently when playing a macro, it uses one input only, so when you use the "flip 2 player controls" option it straight up just doesnt work on 2p levels

**Comment by ZiLko** [comment]
I think i fixed it
