### ISSUE TITLE
This mod is incompatible

### ISSUE THREAD

**Issue by Faisalkhan2266** [ZiLko/xdBot#93]
The mod definitely need an update to the latest version of geode and GD 2.206. I hope you work on update it.

Thank you

**Comment by ZiLko** [comment]
is geode even out for 2.206 yet

**Comment by Faisalkhan2266** [comment]
> is geode even out for 2.206 yet

Yes it did. The geode version is 3.0.0 Alpha 2 and the geode version that's currently working on is Geometry Dash 2.206. Let me attach screenshots.
![Screenshot_20240612_062755_Geode](https://github.com/ZiLko/xdBot/assets/159558539/b5ec9b4a-128f-49c8-a9bd-5e2e2983289e)
![Screenshot_20240612_062804_Geode](https://github.com/ZiLko/xdBot/assets/159558539/496485e3-9173-43cb-8d01-bccfbb914176)

**Comment by Faisalkhan2266** [comment]
I think you have to upload the mod to Geode 3.0. The entire UI got Changed plus it has more details about mods. Like downloads info, social info if you need credit, you can attached discord and YouTube channel I guess. The list goes on

**Comment by Faisalkhan2266** [comment]
> not officially out yet

If it's out or not but the mods are getting updated to the latest version of Geode

**Comment by ZiLko** [comment]
ill release a 2.206 working version when i get it to work
